// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.mtproto.client.dh.`inner`

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("client_DH_inner_data")
@TLCombinatorId(0x6643B654)
public data class ClientDHInnerData(
    @TLFixedSize(value = 16)
    @get:JvmName("nonce")
    public val nonce: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @SerialName("server_nonce")
    @TLFixedSize(value = 16)
    @get:JvmName("serverNonce")
    public val serverNonce: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @SerialName("retry_id")
    @get:JvmName("retryId")
    public val retryId: Long,
    @SerialName("g_b")
    @get:JvmName("gB")
    public val gB: String,
) {
    public companion object
}
