// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface AutosaveSettingsScope {
    @Serializable
    @SerialName("autosaveSettingsScopePrivateChats")
    @TLCombinatorId(0x5329797F)
    public object AutosaveSettingsScopePrivateChats : AutosaveSettingsScope

    @Serializable
    @SerialName("autosaveSettingsScopeGroupChats")
    @TLCombinatorId(0x32E00E4E)
    public object AutosaveSettingsScopeGroupChats : AutosaveSettingsScope

    @Serializable
    @SerialName("autosaveSettingsScopeChannelChats")
    @TLCombinatorId(0xE2391FD1)
    public object AutosaveSettingsScopeChannelChats : AutosaveSettingsScope

    @Serializable
    @SerialName("autosaveSettingsScopeChat")
    @TLCombinatorId(0x9EB5C2E9)
    public data class AutosaveSettingsScopeChat(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Long,
    ) : AutosaveSettingsScope {
        public companion object
    }

    public companion object
}
