// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("availableReactions")
@TLCombinatorId(0x76F7AEC0)
public data class AvailableReactions(
    @SerialName("top_reactions")
    @get:JvmName("topReactions")
    public val topReactions: List<AvailableReaction>,
    @SerialName("recent_reactions")
    @get:JvmName("recentReactions")
    public val recentReactions: List<AvailableReaction>,
    @SerialName("popular_reactions")
    @get:JvmName("popularReactions")
    public val popularReactions: List<AvailableReaction>,
    @SerialName("allow_custom_emoji")
    @get:JvmName("allowCustomEmoji")
    public val allowCustomEmoji: Boolean,
) {
    public companion object
}
