// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("bankCardActionOpenUrl")
@TLCombinatorId(0xF44A5885)
public data class BankCardActionOpenUrl(
    @get:JvmName("text")
    public val text: String,
    @get:JvmName("url")
    public val url: String,
) {
    public companion object
}
