// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class BlockList {
    @SerialName("blockListMain")
    @TLCombinatorId(0x50A4137C)
    BLOCK_LIST_MAIN,
    @SerialName("blockListStories")
    @TLCombinatorId(0x0628965C)
    BLOCK_LIST_STORIES,
    ;

    public companion object
}
