// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface ChatMemberStatus {
    @Serializable
    @SerialName("chatMemberStatusCreator")
    @TLCombinatorId(0xF6764AFE)
    public data class ChatMemberStatusCreator(
        @SerialName("custom_title")
        @get:JvmName("customTitle")
        public val customTitle: String,
        @SerialName("is_anonymous")
        @get:JvmName("isAnonymous")
        public val isAnonymous: Boolean,
        @SerialName("is_member")
        @get:JvmName("isMember")
        public val isMember: Boolean,
    ) : ChatMemberStatus {
        public companion object
    }

    @Serializable
    @SerialName("chatMemberStatusAdministrator")
    @TLCombinatorId(0xFBD3841D)
    public data class ChatMemberStatusAdministrator(
        @SerialName("custom_title")
        @get:JvmName("customTitle")
        public val customTitle: String,
        @SerialName("can_be_edited")
        @get:JvmName("canBeEdited")
        public val canBeEdited: Boolean,
        @get:JvmName("rights")
        public val rights: ChatAdministratorRights,
    ) : ChatMemberStatus {
        public companion object
    }

    @Serializable
    @SerialName("chatMemberStatusMember")
    @TLCombinatorId(0x32597455)
    public object ChatMemberStatusMember : ChatMemberStatus

    @Serializable
    @SerialName("chatMemberStatusRestricted")
    @TLCombinatorId(0x630774A6)
    public data class ChatMemberStatusRestricted(
        @SerialName("is_member")
        @get:JvmName("isMember")
        public val isMember: Boolean,
        @SerialName("restricted_until_date")
        @get:JvmName("restrictedUntilDate")
        public val restrictedUntilDate: Int,
        @get:JvmName("permissions")
        public val permissions: ChatPermissions,
    ) : ChatMemberStatus {
        public companion object
    }

    @Serializable
    @SerialName("chatMemberStatusLeft")
    @TLCombinatorId(0xFFA74425)
    public object ChatMemberStatusLeft : ChatMemberStatus

    @Serializable
    @SerialName("chatMemberStatusBanned")
    @TLCombinatorId(0x9D714EB6)
    public data class ChatMemberStatusBanned(
        @SerialName("banned_until_date")
        @get:JvmName("bannedUntilDate")
        public val bannedUntilDate: Int,
    ) : ChatMemberStatus {
        public companion object
    }

    public companion object
}
