// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("chatBoostLink")
@TLCombinatorId(0xB5417C71)
public data class ChatBoostLink(
    @get:JvmName("link")
    public val link: String,
    @SerialName("is_public")
    @get:JvmName("isPublic")
    public val isPublic: Boolean,
) {
    public companion object
}
