// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("chatAdministratorRights")
@TLCombinatorId(0x5F4F9044)
public data class ChatAdministratorRights(
    @SerialName("can_manage_chat")
    @get:JvmName("canManageChat")
    public val canManageChat: Boolean,
    @SerialName("can_change_info")
    @get:JvmName("canChangeInfo")
    public val canChangeInfo: Boolean,
    @SerialName("can_post_messages")
    @get:JvmName("canPostMessages")
    public val canPostMessages: Boolean,
    @SerialName("can_edit_messages")
    @get:JvmName("canEditMessages")
    public val canEditMessages: Boolean,
    @SerialName("can_delete_messages")
    @get:JvmName("canDeleteMessages")
    public val canDeleteMessages: Boolean,
    @SerialName("can_invite_users")
    @get:JvmName("canInviteUsers")
    public val canInviteUsers: Boolean,
    @SerialName("can_restrict_members")
    @get:JvmName("canRestrictMembers")
    public val canRestrictMembers: Boolean,
    @SerialName("can_pin_messages")
    @get:JvmName("canPinMessages")
    public val canPinMessages: Boolean,
    @SerialName("can_manage_topics")
    @get:JvmName("canManageTopics")
    public val canManageTopics: Boolean,
    @SerialName("can_promote_members")
    @get:JvmName("canPromoteMembers")
    public val canPromoteMembers: Boolean,
    @SerialName("can_manage_video_chats")
    @get:JvmName("canManageVideoChats")
    public val canManageVideoChats: Boolean,
    @SerialName("can_post_stories")
    @get:JvmName("canPostStories")
    public val canPostStories: Boolean,
    @SerialName("can_edit_stories")
    @get:JvmName("canEditStories")
    public val canEditStories: Boolean,
    @SerialName("can_delete_stories")
    @get:JvmName("canDeleteStories")
    public val canDeleteStories: Boolean,
    @SerialName("is_anonymous")
    @get:JvmName("isAnonymous")
    public val isAnonymous: Boolean,
) {
    public companion object
}
