// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("chatPhotoSticker")
@TLCombinatorId(0xA90383A3)
public data class ChatPhotoSticker(
    @get:JvmName("type")
    public val type: ChatPhotoStickerType,
    @SerialName("background_fill")
    @get:JvmName("backgroundFill")
    public val backgroundFill: BackgroundFill,
) {
    public companion object
}
