// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface ChatStatistics {
    @Serializable
    @SerialName("chatStatisticsSupergroup")
    @TLCombinatorId(0xFEF8DE27)
    public data class ChatStatisticsSupergroup(
        @get:JvmName("period")
        public val period: DateRange,
        @SerialName("member_count")
        @get:JvmName("memberCount")
        public val memberCount: StatisticalValue,
        @SerialName("message_count")
        @get:JvmName("messageCount")
        public val messageCount: StatisticalValue,
        @SerialName("viewer_count")
        @get:JvmName("viewerCount")
        public val viewerCount: StatisticalValue,
        @SerialName("sender_count")
        @get:JvmName("senderCount")
        public val senderCount: StatisticalValue,
        @SerialName("member_count_graph")
        @get:JvmName("memberCountGraph")
        public val memberCountGraph: StatisticalGraph,
        @SerialName("join_graph")
        @get:JvmName("joinGraph")
        public val joinGraph: StatisticalGraph,
        @SerialName("join_by_source_graph")
        @get:JvmName("joinBySourceGraph")
        public val joinBySourceGraph: StatisticalGraph,
        @SerialName("language_graph")
        @get:JvmName("languageGraph")
        public val languageGraph: StatisticalGraph,
        @SerialName("message_content_graph")
        @get:JvmName("messageContentGraph")
        public val messageContentGraph: StatisticalGraph,
        @SerialName("action_graph")
        @get:JvmName("actionGraph")
        public val actionGraph: StatisticalGraph,
        @SerialName("day_graph")
        @get:JvmName("dayGraph")
        public val dayGraph: StatisticalGraph,
        @SerialName("week_graph")
        @get:JvmName("weekGraph")
        public val weekGraph: StatisticalGraph,
        @SerialName("top_senders")
        @get:JvmName("topSenders")
        public val topSenders: List<ChatStatisticsMessageSenderInfo>,
        @SerialName("top_administrators")
        @get:JvmName("topAdministrators")
        public val topAdministrators: List<ChatStatisticsAdministratorActionsInfo>,
        @SerialName("top_inviters")
        @get:JvmName("topInviters")
        public val topInviters: List<ChatStatisticsInviterInfo>,
    ) : ChatStatistics {
        public companion object
    }

    @Serializable
    @SerialName("chatStatisticsChannel")
    @TLCombinatorId(0xCECCDFB9)
    public data class ChatStatisticsChannel(
        @get:JvmName("period")
        public val period: DateRange,
        @SerialName("member_count")
        @get:JvmName("memberCount")
        public val memberCount: StatisticalValue,
        @SerialName("mean_view_count")
        @get:JvmName("meanViewCount")
        public val meanViewCount: StatisticalValue,
        @SerialName("mean_share_count")
        @get:JvmName("meanShareCount")
        public val meanShareCount: StatisticalValue,
        @SerialName("enabled_notifications_percentage")
        @get:JvmName("enabledNotificationsPercentage")
        public val enabledNotificationsPercentage: Double,
        @SerialName("member_count_graph")
        @get:JvmName("memberCountGraph")
        public val memberCountGraph: StatisticalGraph,
        @SerialName("join_graph")
        @get:JvmName("joinGraph")
        public val joinGraph: StatisticalGraph,
        @SerialName("mute_graph")
        @get:JvmName("muteGraph")
        public val muteGraph: StatisticalGraph,
        @SerialName("view_count_by_hour_graph")
        @get:JvmName("viewCountByHourGraph")
        public val viewCountByHourGraph: StatisticalGraph,
        @SerialName("view_count_by_source_graph")
        @get:JvmName("viewCountBySourceGraph")
        public val viewCountBySourceGraph: StatisticalGraph,
        @SerialName("join_by_source_graph")
        @get:JvmName("joinBySourceGraph")
        public val joinBySourceGraph: StatisticalGraph,
        @SerialName("language_graph")
        @get:JvmName("languageGraph")
        public val languageGraph: StatisticalGraph,
        @SerialName("message_interaction_graph")
        @get:JvmName("messageInteractionGraph")
        public val messageInteractionGraph: StatisticalGraph,
        @SerialName("instant_view_interaction_graph")
        @get:JvmName("instantViewInteractionGraph")
        public val instantViewInteractionGraph: StatisticalGraph,
        @SerialName("recent_message_interactions")
        @get:JvmName("recentMessageInteractions")
        public val recentMessageInteractions: List<ChatStatisticsMessageInteractionInfo>,
    ) : ChatStatistics {
        public companion object
    }

    public companion object
}
