// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface ChatPhotoStickerType {
    @Serializable
    @SerialName("chatPhotoStickerTypeRegularOrMask")
    @TLCombinatorId(0xE741599C)
    public data class ChatPhotoStickerTypeRegularOrMask(
        @SerialName("sticker_set_id")
        @get:JvmName("stickerSetId")
        public val stickerSetId: Long,
        @SerialName("sticker_id")
        @get:JvmName("stickerId")
        public val stickerId: Long,
    ) : ChatPhotoStickerType {
        public companion object
    }

    @Serializable
    @SerialName("chatPhotoStickerTypeCustomEmoji")
    @TLCombinatorId(0xF021BAD1)
    public data class ChatPhotoStickerTypeCustomEmoji(
        @SerialName("custom_emoji_id")
        @get:JvmName("customEmojiId")
        public val customEmojiId: Long,
    ) : ChatPhotoStickerType {
        public companion object
    }

    public companion object
}
