// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface ChatAction {
    @Serializable
    @SerialName("chatActionTyping")
    @TLCombinatorId(0x16A83437)
    public object ChatActionTyping : ChatAction

    @Serializable
    @SerialName("chatActionRecordingVideo")
    @TLCombinatorId(0x0CE85792)
    public object ChatActionRecordingVideo : ChatAction

    @Serializable
    @SerialName("chatActionUploadingVideo")
    @TLCombinatorId(0x49902C36)
    public data class ChatActionUploadingVideo(
        @get:JvmName("progress")
        public val progress: Int,
    ) : ChatAction {
        public companion object
    }

    @Serializable
    @SerialName("chatActionRecordingVoiceNote")
    @TLCombinatorId(0xCFC9ED76)
    public object ChatActionRecordingVoiceNote : ChatAction

    @Serializable
    @SerialName("chatActionUploadingVoiceNote")
    @TLCombinatorId(0xDB6C8A6E)
    public data class ChatActionUploadingVoiceNote(
        @get:JvmName("progress")
        public val progress: Int,
    ) : ChatAction {
        public companion object
    }

    @Serializable
    @SerialName("chatActionUploadingPhoto")
    @TLCombinatorId(0x26FEEB47)
    public data class ChatActionUploadingPhoto(
        @get:JvmName("progress")
        public val progress: Int,
    ) : ChatAction {
        public companion object
    }

    @Serializable
    @SerialName("chatActionUploadingDocument")
    @TLCombinatorId(0x0A01B64A)
    public data class ChatActionUploadingDocument(
        @get:JvmName("progress")
        public val progress: Int,
    ) : ChatAction {
        public companion object
    }

    @Serializable
    @SerialName("chatActionChoosingSticker")
    @TLCombinatorId(0x1637C521)
    public object ChatActionChoosingSticker : ChatAction

    @Serializable
    @SerialName("chatActionChoosingLocation")
    @TLCombinatorId(0x87B96324)
    public object ChatActionChoosingLocation : ChatAction

    @Serializable
    @SerialName("chatActionChoosingContact")
    @TLCombinatorId(0xB7220418)
    public object ChatActionChoosingContact : ChatAction

    @Serializable
    @SerialName("chatActionStartPlayingGame")
    @TLCombinatorId(0xCC63A7FC)
    public object ChatActionStartPlayingGame : ChatAction

    @Serializable
    @SerialName("chatActionRecordingVideoNote")
    @TLCombinatorId(0x00FC2081)
    public object ChatActionRecordingVideoNote : ChatAction

    @Serializable
    @SerialName("chatActionUploadingVideoNote")
    @TLCombinatorId(0x45E0DE76)
    public data class ChatActionUploadingVideoNote(
        @get:JvmName("progress")
        public val progress: Int,
    ) : ChatAction {
        public companion object
    }

    @Serializable
    @SerialName("chatActionWatchingAnimations")
    @TLCombinatorId(0x7A5E26B1)
    public data class ChatActionWatchingAnimations(
        @get:JvmName("emoji")
        public val emoji: String,
    ) : ChatAction {
        public companion object
    }

    @Serializable
    @SerialName("chatActionCancel")
    @TLCombinatorId(0x452C30B6)
    public object ChatActionCancel : ChatAction

    public companion object
}
