// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("chatInviteLinks")
@TLCombinatorId(0x06BA9623)
public data class ChatInviteLinks(
    @SerialName("total_count")
    @get:JvmName("totalCount")
    public val totalCount: Int,
    @SerialName("invite_links")
    @get:JvmName("inviteLinks")
    public val inviteLinks: List<ChatInviteLink>,
) {
    public companion object
}
