// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface ChatType {
    @Serializable
    @SerialName("chatTypePrivate")
    @TLCombinatorId(0x5E1E6374)
    public data class ChatTypePrivate(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
    ) : ChatType {
        public companion object
    }

    @Serializable
    @SerialName("chatTypeBasicGroup")
    @TLCombinatorId(0x3A0C4C5C)
    public data class ChatTypeBasicGroup(
        @SerialName("basic_group_id")
        @get:JvmName("basicGroupId")
        public val basicGroupId: Long,
    ) : ChatType {
        public companion object
    }

    @Serializable
    @SerialName("chatTypeSupergroup")
    @TLCombinatorId(0xA83A5A6A)
    public data class ChatTypeSupergroup(
        @SerialName("supergroup_id")
        @get:JvmName("supergroupId")
        public val supergroupId: Long,
        @SerialName("is_channel")
        @get:JvmName("isChannel")
        public val isChannel: Boolean,
    ) : ChatType {
        public companion object
    }

    @Serializable
    @SerialName("chatTypeSecret")
    @TLCombinatorId(0x3366AB31)
    public data class ChatTypeSecret(
        @SerialName("secret_chat_id")
        @get:JvmName("secretChatId")
        public val secretChatId: Int,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
    ) : ChatType {
        public companion object
    }

    public companion object
}
