// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("closedVectorPath")
@TLCombinatorId(0x2329F2A9)
public data class ClosedVectorPath(
    @get:JvmName("commands")
    public val commands: List<VectorPathCommand>,
) {
    public companion object
}
