// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("contact")
@TLCombinatorId(0x89285774)
public data class Contact(
    @SerialName("phone_number")
    @get:JvmName("phoneNumber")
    public val phoneNumber: String,
    @SerialName("first_name")
    @get:JvmName("firstName")
    public val firstName: String,
    @SerialName("last_name")
    @get:JvmName("lastName")
    public val lastName: String,
    @get:JvmName("vcard")
    public val vcard: String,
    @SerialName("user_id")
    @get:JvmName("userId")
    public val userId: Long,
) {
    public companion object
}
