// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("count")
@TLCombinatorId(0x4D38F104)
public data class Count(
    @get:JvmName("count")
    public val count: Int,
) {
    public companion object
}
