// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("document")
@TLCombinatorId(0xAF19AFD8)
public data class Document(
    @SerialName("file_name")
    @get:JvmName("fileName")
    public val fileName: String,
    @SerialName("mime_type")
    @get:JvmName("mimeType")
    public val mimeType: String,
    @get:JvmName("minithumbnail")
    public val minithumbnail: Minithumbnail,
    @get:JvmName("thumbnail")
    public val thumbnail: Thumbnail,
    @get:JvmName("document")
    public val document: File,
) {
    public companion object
}
