// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("draftMessage")
@TLCombinatorId(0xF67C6A5C)
public data class DraftMessage(
    @SerialName("reply_to")
    @get:JvmName("replyTo")
    public val replyTo: InputMessageReplyTo,
    @get:JvmName("date")
    public val date: Int,
    @SerialName("input_message_text")
    @get:JvmName("inputMessageText")
    public val inputMessageText: InputMessageContent,
) {
    public companion object
}
