// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("emailAddressAuthenticationCodeInfo")
@TLCombinatorId(0x449BE223)
public data class EmailAddressAuthenticationCodeInfo(
    @SerialName("email_address_pattern")
    @get:JvmName("emailAddressPattern")
    public val emailAddressPattern: String,
    @get:JvmName("length")
    public val length: Int,
) {
    public companion object
}
