// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("emojiStatuses")
@TLCombinatorId(0xE97A51F6)
public data class EmojiStatuses(
    @SerialName("custom_emoji_ids")
    @get:JvmName("customEmojiIds")
    public val customEmojiIds: List<Long>,
) {
    public companion object
}
