// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("emojiCategory")
@TLCombinatorId(0x3CC2B640)
public data class EmojiCategory(
    @get:JvmName("name")
    public val name: String,
    @get:JvmName("icon")
    public val icon: Sticker,
    @get:JvmName("emojis")
    public val emojis: List<String>,
) {
    public companion object
}
