// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class FileType {
    @SerialName("fileTypeNone")
    @TLCombinatorId(0x77637EA5)
    FILE_TYPE_NONE,
    @SerialName("fileTypeAnimation")
    @TLCombinatorId(0xEEAA7DBA)
    FILE_TYPE_ANIMATION,
    @SerialName("fileTypeAudio")
    @TLCombinatorId(0xD5BBCEA0)
    FILE_TYPE_AUDIO,
    @SerialName("fileTypeDocument")
    @TLCombinatorId(0xDE57030F)
    FILE_TYPE_DOCUMENT,
    @SerialName("fileTypeNotificationSound")
    @TLCombinatorId(0xC32F9F09)
    FILE_TYPE_NOTIFICATION_SOUND,
    @SerialName("fileTypePhoto")
    @TLCombinatorId(0x998B71A5)
    FILE_TYPE_PHOTO,
    @SerialName("fileTypePhotoStory")
    @TLCombinatorId(0x78576EF4)
    FILE_TYPE_PHOTO_STORY,
    @SerialName("fileTypeProfilePhoto")
    @TLCombinatorId(0x6AFEE3A3)
    FILE_TYPE_PROFILE_PHOTO,
    @SerialName("fileTypeSecret")
    @TLCombinatorId(0x906D14F7)
    FILE_TYPE_SECRET,
    @SerialName("fileTypeSecretThumbnail")
    @TLCombinatorId(0xAC797636)
    FILE_TYPE_SECRET_THUMBNAIL,
    @SerialName("fileTypeSecure")
    @TLCombinatorId(0xAB69BF26)
    FILE_TYPE_SECURE,
    @SerialName("fileTypeSticker")
    @TLCombinatorId(0x1C537C69)
    FILE_TYPE_STICKER,
    @SerialName("fileTypeThumbnail")
    @TLCombinatorId(0xFF42215E)
    FILE_TYPE_THUMBNAIL,
    @SerialName("fileTypeUnknown")
    @TLCombinatorId(0x8819ED50)
    FILE_TYPE_UNKNOWN,
    @SerialName("fileTypeVideo")
    @TLCombinatorId(0x5548871B)
    FILE_TYPE_VIDEO,
    @SerialName("fileTypeVideoNote")
    @TLCombinatorId(0xE119A79F)
    FILE_TYPE_VIDEO_NOTE,
    @SerialName("fileTypeVideoStory")
    @TLCombinatorId(0x800B21A1)
    FILE_TYPE_VIDEO_STORY,
    @SerialName("fileTypeVoiceNote")
    @TLCombinatorId(0xDCE96E43)
    FILE_TYPE_VOICE_NOTE,
    @SerialName("fileTypeWallpaper")
    @TLCombinatorId(0x6E8FFC9C)
    FILE_TYPE_WALLPAPER,
    ;

    public companion object
}
