// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface FirebaseAuthenticationSettings {
    @Serializable
    @SerialName("firebaseAuthenticationSettingsAndroid")
    @TLCombinatorId(0x966EF61C)
    public object FirebaseAuthenticationSettingsAndroid : FirebaseAuthenticationSettings

    @Serializable
    @SerialName("firebaseAuthenticationSettingsIos")
    @TLCombinatorId(0x0D49A4C4)
    public data class FirebaseAuthenticationSettingsIos(
        @SerialName("device_token")
        @get:JvmName("deviceToken")
        public val deviceToken: String,
        @SerialName("is_app_sandbox")
        @get:JvmName("isAppSandbox")
        public val isAppSandbox: Boolean,
    ) : FirebaseAuthenticationSettings {
        public companion object
    }

    public companion object
}
