// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("forumTopics")
@TLCombinatorId(0x2BADF051)
public data class ForumTopics(
    @SerialName("total_count")
    @get:JvmName("totalCount")
    public val totalCount: Int,
    @get:JvmName("topics")
    public val topics: List<ForumTopic>,
    @SerialName("next_offset_date")
    @get:JvmName("nextOffsetDate")
    public val nextOffsetDate: Int,
    @SerialName("next_offset_message_id")
    @get:JvmName("nextOffsetMessageId")
    public val nextOffsetMessageId: Long,
    @SerialName("next_offset_message_thread_id")
    @get:JvmName("nextOffsetMessageThreadId")
    public val nextOffsetMessageThreadId: Long,
) {
    public companion object
}
