// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("foundFileDownloads")
@TLCombinatorId(0x533398D8)
public data class FoundFileDownloads(
    @SerialName("total_counts")
    @get:JvmName("totalCounts")
    public val totalCounts: DownloadedFileCounts,
    @get:JvmName("files")
    public val files: List<FileDownload>,
    @SerialName("next_offset")
    @get:JvmName("nextOffset")
    public val nextOffset: String,
) {
    public companion object
}
