// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("groupCallStream")
@TLCombinatorId(0xF03B0FC5)
public data class GroupCallStream(
    @SerialName("channel_id")
    @get:JvmName("channelId")
    public val channelId: Int,
    @get:JvmName("scale")
    public val scale: Int,
    @SerialName("time_offset")
    @get:JvmName("timeOffset")
    public val timeOffset: Long,
) {
    public companion object
}
