// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("groupCallId")
@TLCombinatorId(0x14E4BB45)
public data class GroupCallId(
    @get:JvmName("id")
    public val id: Int,
) {
    public companion object
}
