// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("inputStoryAreas")
@TLCombinatorId(0xCB5AB810)
public data class InputStoryAreas(
    @get:JvmName("areas")
    public val areas: List<InputStoryArea>,
) {
    public companion object
}
