// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface InputInvoice {
    @Serializable
    @SerialName("inputInvoiceMessage")
    @TLCombinatorId(0x58DCEA10)
    public data class InputInvoiceMessage(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Long,
        @SerialName("message_id")
        @get:JvmName("messageId")
        public val messageId: Long,
    ) : InputInvoice {
        public companion object
    }

    @Serializable
    @SerialName("inputInvoiceName")
    @TLCombinatorId(0xB1CA16F3)
    public data class InputInvoiceName(
        @get:JvmName("name")
        public val name: String,
    ) : InputInvoice {
        public companion object
    }

    @Serializable
    @SerialName("inputInvoiceTelegram")
    @TLCombinatorId(0x96ECFEED)
    public data class InputInvoiceTelegram(
        @get:JvmName("purpose")
        public val purpose: TelegramPaymentPurpose,
    ) : InputInvoice {
        public companion object
    }

    public companion object
}
