// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("inputPersonalDocument")
@TLCombinatorId(0x63F47BAA)
public data class InputPersonalDocument(
    @get:JvmName("files")
    public val files: List<InputFile>,
    @get:JvmName("translation")
    public val translation: List<InputFile>,
) {
    public companion object
}
