// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface InputMessageContent {
    @Serializable
    @SerialName("inputMessageText")
    @TLCombinatorId(0xF350D894)
    public data class InputMessageText(
        @get:JvmName("text")
        public val text: FormattedText,
        @SerialName("link_preview_options")
        @get:JvmName("linkPreviewOptions")
        public val linkPreviewOptions: LinkPreviewOptions,
        @SerialName("clear_draft")
        @get:JvmName("clearDraft")
        public val clearDraft: Boolean,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageAnimation")
    @TLCombinatorId(0x32B56C89)
    public data class InputMessageAnimation(
        @get:JvmName("animation")
        public val animation: InputFile,
        @get:JvmName("thumbnail")
        public val thumbnail: InputThumbnail,
        @SerialName("added_sticker_file_ids")
        @get:JvmName("addedStickerFileIds")
        public val addedStickerFileIds: List<Int>,
        @get:JvmName("duration")
        public val duration: Int,
        @get:JvmName("width")
        public val width: Int,
        @get:JvmName("height")
        public val height: Int,
        @get:JvmName("caption")
        public val caption: FormattedText,
        @SerialName("has_spoiler")
        @get:JvmName("hasSpoiler")
        public val hasSpoiler: Boolean,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageAudio")
    @TLCombinatorId(0xDAA400B2)
    public data class InputMessageAudio(
        @get:JvmName("audio")
        public val audio: InputFile,
        @SerialName("album_cover_thumbnail")
        @get:JvmName("albumCoverThumbnail")
        public val albumCoverThumbnail: InputThumbnail,
        @get:JvmName("duration")
        public val duration: Int,
        @get:JvmName("title")
        public val title: String,
        @get:JvmName("performer")
        public val performer: String,
        @get:JvmName("caption")
        public val caption: FormattedText,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageDocument")
    @TLCombinatorId(0x615B72B9)
    public data class InputMessageDocument(
        @get:JvmName("document")
        public val document: InputFile,
        @get:JvmName("thumbnail")
        public val thumbnail: InputThumbnail,
        @SerialName("disable_content_type_detection")
        @get:JvmName("disableContentTypeDetection")
        public val disableContentTypeDetection: Boolean,
        @get:JvmName("caption")
        public val caption: FormattedText,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessagePhoto")
    @TLCombinatorId(0xA8EB87C7)
    public data class InputMessagePhoto(
        @get:JvmName("photo")
        public val photo: InputFile,
        @get:JvmName("thumbnail")
        public val thumbnail: InputThumbnail,
        @SerialName("added_sticker_file_ids")
        @get:JvmName("addedStickerFileIds")
        public val addedStickerFileIds: List<Int>,
        @get:JvmName("width")
        public val width: Int,
        @get:JvmName("height")
        public val height: Int,
        @get:JvmName("caption")
        public val caption: FormattedText,
        @SerialName("self_destruct_type")
        @get:JvmName("selfDestructType")
        public val selfDestructType: MessageSelfDestructType,
        @SerialName("has_spoiler")
        @get:JvmName("hasSpoiler")
        public val hasSpoiler: Boolean,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageSticker")
    @TLCombinatorId(0x3FF1B6F9)
    public data class InputMessageSticker(
        @get:JvmName("sticker")
        public val sticker: InputFile,
        @get:JvmName("thumbnail")
        public val thumbnail: InputThumbnail,
        @get:JvmName("width")
        public val width: Int,
        @get:JvmName("height")
        public val height: Int,
        @get:JvmName("emoji")
        public val emoji: String,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageVideo")
    @TLCombinatorId(0x7218B06C)
    public data class InputMessageVideo(
        @get:JvmName("video")
        public val video: InputFile,
        @get:JvmName("thumbnail")
        public val thumbnail: InputThumbnail,
        @SerialName("added_sticker_file_ids")
        @get:JvmName("addedStickerFileIds")
        public val addedStickerFileIds: List<Int>,
        @get:JvmName("duration")
        public val duration: Int,
        @get:JvmName("width")
        public val width: Int,
        @get:JvmName("height")
        public val height: Int,
        @SerialName("supports_streaming")
        @get:JvmName("supportsStreaming")
        public val supportsStreaming: Boolean,
        @get:JvmName("caption")
        public val caption: FormattedText,
        @SerialName("self_destruct_type")
        @get:JvmName("selfDestructType")
        public val selfDestructType: MessageSelfDestructType,
        @SerialName("has_spoiler")
        @get:JvmName("hasSpoiler")
        public val hasSpoiler: Boolean,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageVideoNote")
    @TLCombinatorId(0x10A2DCFB)
    public data class InputMessageVideoNote(
        @SerialName("video_note")
        @get:JvmName("videoNote")
        public val videoNote: InputFile,
        @get:JvmName("thumbnail")
        public val thumbnail: InputThumbnail,
        @get:JvmName("duration")
        public val duration: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageVoiceNote")
    @TLCombinatorId(0x7F58B3E9)
    public data class InputMessageVoiceNote(
        @SerialName("voice_note")
        @get:JvmName("voiceNote")
        public val voiceNote: InputFile,
        @get:JvmName("duration")
        public val duration: Int,
        @get:JvmName("waveform")
        public val waveform: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("caption")
        public val caption: FormattedText,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageLocation")
    @TLCombinatorId(0x26AAE970)
    public data class InputMessageLocation(
        @get:JvmName("location")
        public val location: Location,
        @SerialName("live_period")
        @get:JvmName("livePeriod")
        public val livePeriod: Int,
        @get:JvmName("heading")
        public val heading: Int,
        @SerialName("proximity_alert_radius")
        @get:JvmName("proximityAlertRadius")
        public val proximityAlertRadius: Int,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageVenue")
    @TLCombinatorId(0x564D99FD)
    public data class InputMessageVenue(
        @get:JvmName("venue")
        public val venue: Venue,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageContact")
    @TLCombinatorId(0xC5710CFF)
    public data class InputMessageContact(
        @get:JvmName("contact")
        public val contact: Contact,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageDice")
    @TLCombinatorId(0x322967A9)
    public data class InputMessageDice(
        @get:JvmName("emoji")
        public val emoji: String,
        @SerialName("clear_draft")
        @get:JvmName("clearDraft")
        public val clearDraft: Boolean,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageGame")
    @TLCombinatorId(0x4AAE6AE2)
    public data class InputMessageGame(
        @SerialName("bot_user_id")
        @get:JvmName("botUserId")
        public val botUserId: Long,
        @SerialName("game_short_name")
        @get:JvmName("gameShortName")
        public val gameShortName: String,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageInvoice")
    @TLCombinatorId(0x34CD1D60)
    public data class InputMessageInvoice(
        @get:JvmName("invoice")
        public val invoice: Invoice,
        @get:JvmName("title")
        public val title: String,
        @get:JvmName("description")
        public val description: String,
        @SerialName("photo_url")
        @get:JvmName("photoUrl")
        public val photoUrl: String,
        @SerialName("photo_size")
        @get:JvmName("photoSize")
        public val photoSize: Int,
        @SerialName("photo_width")
        @get:JvmName("photoWidth")
        public val photoWidth: Int,
        @SerialName("photo_height")
        @get:JvmName("photoHeight")
        public val photoHeight: Int,
        @get:JvmName("payload")
        public val payload: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("provider_token")
        @get:JvmName("providerToken")
        public val providerToken: String,
        @SerialName("provider_data")
        @get:JvmName("providerData")
        public val providerData: String,
        @SerialName("start_parameter")
        @get:JvmName("startParameter")
        public val startParameter: String,
        @SerialName("extended_media_content")
        @get:JvmName("extendedMediaContent")
        public val extendedMediaContent: InputMessageContent,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessagePoll")
    @TLCombinatorId(0x7A772A0C)
    public data class InputMessagePoll(
        @get:JvmName("question")
        public val question: String,
        @get:JvmName("options")
        public val options: List<String>,
        @SerialName("is_anonymous")
        @get:JvmName("isAnonymous")
        public val isAnonymous: Boolean,
        @get:JvmName("type")
        public val type: PollType,
        @SerialName("open_period")
        @get:JvmName("openPeriod")
        public val openPeriod: Int,
        @SerialName("close_date")
        @get:JvmName("closeDate")
        public val closeDate: Int,
        @SerialName("is_closed")
        @get:JvmName("isClosed")
        public val isClosed: Boolean,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageStory")
    @TLCombinatorId(0x21099D63)
    public data class InputMessageStory(
        @SerialName("story_sender_chat_id")
        @get:JvmName("storySenderChatId")
        public val storySenderChatId: Long,
        @SerialName("story_id")
        @get:JvmName("storyId")
        public val storyId: Int,
    ) : InputMessageContent {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageForwarded")
    @TLCombinatorId(0x651A73F8)
    public data class InputMessageForwarded(
        @SerialName("from_chat_id")
        @get:JvmName("fromChatId")
        public val fromChatId: Long,
        @SerialName("message_id")
        @get:JvmName("messageId")
        public val messageId: Long,
        @SerialName("in_game_share")
        @get:JvmName("inGameShare")
        public val inGameShare: Boolean,
        @SerialName("copy_options")
        @get:JvmName("copyOptions")
        public val copyOptions: MessageCopyOptions,
    ) : InputMessageContent {
        public companion object
    }

    public companion object
}
