// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface InputBackground {
    @Serializable
    @SerialName("inputBackgroundLocal")
    @TLCombinatorId(0x97DD74A4)
    public data class InputBackgroundLocal(
        @get:JvmName("background")
        public val background: InputFile,
    ) : InputBackground {
        public companion object
    }

    @Serializable
    @SerialName("inputBackgroundRemote")
    @TLCombinatorId(0xEF9C3219)
    public data class InputBackgroundRemote(
        @SerialName("background_id")
        @get:JvmName("backgroundId")
        public val backgroundId: Long,
    ) : InputBackground {
        public companion object
    }

    @Serializable
    @SerialName("inputBackgroundPrevious")
    @TLCombinatorId(0xEB06575E)
    public data class InputBackgroundPrevious(
        @SerialName("message_id")
        @get:JvmName("messageId")
        public val messageId: Long,
    ) : InputBackground {
        public companion object
    }

    public companion object
}
