// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("inputThumbnail")
@TLCombinatorId(0x5E515024)
public data class InputThumbnail(
    @get:JvmName("thumbnail")
    public val thumbnail: InputFile,
    @get:JvmName("width")
    public val width: Int,
    @get:JvmName("height")
    public val height: Int,
) {
    public companion object
}
