// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("languagePackStrings")
@TLCombinatorId(0x45DC90EA)
public data class LanguagePackStrings(
    @get:JvmName("strings")
    public val strings: List<LanguagePackString>,
) {
    public companion object
}
