// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("linkPreviewOptions")
@TLCombinatorId(0x3E61B3F3)
public data class LinkPreviewOptions(
    @SerialName("is_disabled")
    @get:JvmName("isDisabled")
    public val isDisabled: Boolean,
    @get:JvmName("url")
    public val url: String,
    @SerialName("force_small_media")
    @get:JvmName("forceSmallMedia")
    public val forceSmallMedia: Boolean,
    @SerialName("force_large_media")
    @get:JvmName("forceLargeMedia")
    public val forceLargeMedia: Boolean,
    @SerialName("show_above_text")
    @get:JvmName("showAboveText")
    public val showAboveText: Boolean,
) {
    public companion object
}
