// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("localizationTargetInfo")
@TLCombinatorId(0x85E3C3A7)
public data class LocalizationTargetInfo(
    @SerialName("language_packs")
    @get:JvmName("languagePacks")
    public val languagePacks: List<LanguagePackInfo>,
) {
    public companion object
}
