// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("logVerbosityLevel")
@TLCombinatorId(0x676443EA)
public data class LogVerbosityLevel(
    @SerialName("verbosity_level")
    @get:JvmName("verbosityLevel")
    public val verbosityLevel: Int,
) {
    public companion object
}
