// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("messageCopyOptions")
@TLCombinatorId(0x48076039)
public data class MessageCopyOptions(
    @SerialName("send_copy")
    @get:JvmName("sendCopy")
    public val sendCopy: Boolean,
    @SerialName("replace_caption")
    @get:JvmName("replaceCaption")
    public val replaceCaption: Boolean,
    @SerialName("new_caption")
    @get:JvmName("newCaption")
    public val newCaption: FormattedText,
) {
    public companion object
}
