// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface MessageSendingState {
    @Serializable
    @SerialName("messageSendingStatePending")
    @TLCombinatorId(0xF32B63B4)
    public data class MessageSendingStatePending(
        @SerialName("sending_id")
        @get:JvmName("sendingId")
        public val sendingId: Int,
    ) : MessageSendingState {
        public companion object
    }

    @Serializable
    @SerialName("messageSendingStateFailed")
    @TLCombinatorId(0xAC81EE5E)
    public data class MessageSendingStateFailed(
        @get:JvmName("error")
        public val error: Error,
        @SerialName("can_retry")
        @get:JvmName("canRetry")
        public val canRetry: Boolean,
        @SerialName("need_another_sender")
        @get:JvmName("needAnotherSender")
        public val needAnotherSender: Boolean,
        @SerialName("need_another_reply_quote")
        @get:JvmName("needAnotherReplyQuote")
        public val needAnotherReplyQuote: Boolean,
        @SerialName("need_drop_reply")
        @get:JvmName("needDropReply")
        public val needDropReply: Boolean,
        @SerialName("retry_after")
        @get:JvmName("retryAfter")
        public val retryAfter: Double,
    ) : MessageSendingState {
        public companion object
    }

    public companion object
}
