// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("messageReaction")
@TLCombinatorId(0xBECAF87F)
public data class MessageReaction(
    @get:JvmName("type")
    public val type: ReactionType,
    @SerialName("total_count")
    @get:JvmName("totalCount")
    public val totalCount: Int,
    @SerialName("is_chosen")
    @get:JvmName("isChosen")
    public val isChosen: Boolean,
    @SerialName("used_sender_id")
    @get:JvmName("usedSenderId")
    public val usedSenderId: MessageSender,
    @SerialName("recent_sender_ids")
    @get:JvmName("recentSenderIds")
    public val recentSenderIds: List<MessageSender>,
) {
    public companion object
}
