// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface MessageOrigin {
    @Serializable
    @SerialName("messageOriginUser")
    @TLCombinatorId(0x9C009043)
    public data class MessageOriginUser(
        @SerialName("sender_user_id")
        @get:JvmName("senderUserId")
        public val senderUserId: Long,
    ) : MessageOrigin {
        public companion object
    }

    @Serializable
    @SerialName("messageOriginHiddenUser")
    @TLCombinatorId(0xED0C23DA)
    public data class MessageOriginHiddenUser(
        @SerialName("sender_name")
        @get:JvmName("senderName")
        public val senderName: String,
    ) : MessageOrigin {
        public companion object
    }

    @Serializable
    @SerialName("messageOriginChat")
    @TLCombinatorId(0xF3BB5EB4)
    public data class MessageOriginChat(
        @SerialName("sender_chat_id")
        @get:JvmName("senderChatId")
        public val senderChatId: Long,
        @SerialName("author_signature")
        @get:JvmName("authorSignature")
        public val authorSignature: String,
    ) : MessageOrigin {
        public companion object
    }

    @Serializable
    @SerialName("messageOriginChannel")
    @TLCombinatorId(0xA97B51BE)
    public data class MessageOriginChannel(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Long,
        @SerialName("message_id")
        @get:JvmName("messageId")
        public val messageId: Long,
        @SerialName("author_signature")
        @get:JvmName("authorSignature")
        public val authorSignature: String,
    ) : MessageOrigin {
        public companion object
    }

    public companion object
}
