// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("messageStatistics")
@TLCombinatorId(0xC3B781B0)
public data class MessageStatistics(
    @SerialName("message_interaction_graph")
    @get:JvmName("messageInteractionGraph")
    public val messageInteractionGraph: StatisticalGraph,
) {
    public companion object
}
