// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("messageViewer")
@TLCombinatorId(0x56F111CD)
public data class MessageViewer(
    @SerialName("user_id")
    @get:JvmName("userId")
    public val userId: Long,
    @SerialName("view_date")
    @get:JvmName("viewDate")
    public val viewDate: Int,
) {
    public companion object
}
