// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("networkStatistics")
@TLCombinatorId(0x604B66A4)
public data class NetworkStatistics(
    @SerialName("since_date")
    @get:JvmName("sinceDate")
    public val sinceDate: Int,
    @get:JvmName("entries")
    public val entries: List<NetworkStatisticsEntry>,
) {
    public companion object
}
