// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class NotificationSettingsScope {
    @SerialName("notificationSettingsScopePrivateChats")
    @TLCombinatorId(0x37E04D67)
    NOTIFICATION_SETTINGS_SCOPE_PRIVATE_CHATS,
    @SerialName("notificationSettingsScopeGroupChats")
    @TLCombinatorId(0x483FD1F3)
    NOTIFICATION_SETTINGS_SCOPE_GROUP_CHATS,
    @SerialName("notificationSettingsScopeChannelChats")
    @TLCombinatorId(0x20AA0588)
    NOTIFICATION_SETTINGS_SCOPE_CHANNEL_CHATS,
    ;

    public companion object
}
