// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class PageBlockHorizontalAlignment {
    @SerialName("pageBlockHorizontalAlignmentLeft")
    @TLCombinatorId(0x329627E9)
    PAGE_BLOCK_HORIZONTAL_ALIGNMENT_LEFT,
    @SerialName("pageBlockHorizontalAlignmentCenter")
    @TLCombinatorId(0xC3D8C4EA)
    PAGE_BLOCK_HORIZONTAL_ALIGNMENT_CENTER,
    @SerialName("pageBlockHorizontalAlignmentRight")
    @TLCombinatorId(0x51BD6EFE)
    PAGE_BLOCK_HORIZONTAL_ALIGNMENT_RIGHT,
    ;

    public companion object
}
