// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface PassportElement {
    @Serializable
    @SerialName("passportElementPersonalDetails")
    @TLCombinatorId(0x4894FE83)
    public data class PassportElementPersonalDetails(
        @SerialName("personal_details")
        @get:JvmName("personalDetails")
        public val personalDetails: PersonalDetails,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementPassport")
    @TLCombinatorId(0xF043E723)
    public data class PassportElementPassport(
        @get:JvmName("passport")
        public val passport: IdentityDocument,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementDriverLicense")
    @TLCombinatorId(0x61F70CAD)
    public data class PassportElementDriverLicense(
        @SerialName("driver_license")
        @get:JvmName("driverLicense")
        public val driverLicense: IdentityDocument,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementIdentityCard")
    @TLCombinatorId(0x7C33E535)
    public data class PassportElementIdentityCard(
        @SerialName("identity_card")
        @get:JvmName("identityCard")
        public val identityCard: IdentityDocument,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementInternalPassport")
    @TLCombinatorId(0x0228AD87)
    public data class PassportElementInternalPassport(
        @SerialName("internal_passport")
        @get:JvmName("internalPassport")
        public val internalPassport: IdentityDocument,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementAddress")
    @TLCombinatorId(0xD15A1630)
    public data class PassportElementAddress(
        @get:JvmName("address")
        public val address: Address,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementUtilityBill")
    @TLCombinatorId(0xF2041DD2)
    public data class PassportElementUtilityBill(
        @SerialName("utility_bill")
        @get:JvmName("utilityBill")
        public val utilityBill: PersonalDocument,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementBankStatement")
    @TLCombinatorId(0xEA283268)
    public data class PassportElementBankStatement(
        @SerialName("bank_statement")
        @get:JvmName("bankStatement")
        public val bankStatement: PersonalDocument,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementRentalAgreement")
    @TLCombinatorId(0xEEB4CB28)
    public data class PassportElementRentalAgreement(
        @SerialName("rental_agreement")
        @get:JvmName("rentalAgreement")
        public val rentalAgreement: PersonalDocument,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementPassportRegistration")
    @TLCombinatorId(0x24DADC7F)
    public data class PassportElementPassportRegistration(
        @SerialName("passport_registration")
        @get:JvmName("passportRegistration")
        public val passportRegistration: PersonalDocument,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementTemporaryRegistration")
    @TLCombinatorId(0x49C4AFF0)
    public data class PassportElementTemporaryRegistration(
        @SerialName("temporary_registration")
        @get:JvmName("temporaryRegistration")
        public val temporaryRegistration: PersonalDocument,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementPhoneNumber")
    @TLCombinatorId(0xB1509799)
    public data class PassportElementPhoneNumber(
        @SerialName("phone_number")
        @get:JvmName("phoneNumber")
        public val phoneNumber: String,
    ) : PassportElement {
        public companion object
    }

    @Serializable
    @SerialName("passportElementEmailAddress")
    @TLCombinatorId(0xA4EA9805)
    public data class PassportElementEmailAddress(
        @SerialName("email_address")
        @get:JvmName("emailAddress")
        public val emailAddress: String,
    ) : PassportElement {
        public companion object
    }

    public companion object
}
