// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("passportElements")
@TLCombinatorId(0x4B608854)
public data class PassportElements(
    @get:JvmName("elements")
    public val elements: List<PassportElement>,
) {
    public companion object
}
