// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface PaymentProvider {
    @Serializable
    @SerialName("paymentProviderSmartGlocal")
    @TLCombinatorId(0x6B5122EE)
    public data class PaymentProviderSmartGlocal(
        @SerialName("public_token")
        @get:JvmName("publicToken")
        public val publicToken: String,
    ) : PaymentProvider {
        public companion object
    }

    @Serializable
    @SerialName("paymentProviderStripe")
    @TLCombinatorId(0x1614E19B)
    public data class PaymentProviderStripe(
        @SerialName("publishable_key")
        @get:JvmName("publishableKey")
        public val publishableKey: String,
        @SerialName("need_country")
        @get:JvmName("needCountry")
        public val needCountry: Boolean,
        @SerialName("need_postal_code")
        @get:JvmName("needPostalCode")
        public val needPostalCode: Boolean,
        @SerialName("need_cardholder_name")
        @get:JvmName("needCardholderName")
        public val needCardholderName: Boolean,
    ) : PaymentProvider {
        public companion object
    }

    @Serializable
    @SerialName("paymentProviderOther")
    @TLCombinatorId(0xB050E0E4)
    public data class PaymentProviderOther(
        @get:JvmName("url")
        public val url: String,
    ) : PaymentProvider {
        public companion object
    }

    public companion object
}
