// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("photo")
@TLCombinatorId(0x876D6DE1)
public data class Photo(
    @SerialName("has_stickers")
    @get:JvmName("hasStickers")
    public val hasStickers: Boolean,
    @get:JvmName("minithumbnail")
    public val minithumbnail: Minithumbnail,
    @get:JvmName("sizes")
    public val sizes: List<PhotoSize>,
) {
    public companion object
}
