// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("poll")
@TLCombinatorId(0xACAE8BE0)
public data class Poll(
    @get:JvmName("id")
    public val id: Long,
    @get:JvmName("question")
    public val question: String,
    @get:JvmName("options")
    public val options: List<PollOption>,
    @SerialName("total_voter_count")
    @get:JvmName("totalVoterCount")
    public val totalVoterCount: Int,
    @SerialName("recent_voter_ids")
    @get:JvmName("recentVoterIds")
    public val recentVoterIds: List<MessageSender>,
    @SerialName("is_anonymous")
    @get:JvmName("isAnonymous")
    public val isAnonymous: Boolean,
    @get:JvmName("type")
    public val type: PollType,
    @SerialName("open_period")
    @get:JvmName("openPeriod")
    public val openPeriod: Int,
    @SerialName("close_date")
    @get:JvmName("closeDate")
    public val closeDate: Int,
    @SerialName("is_closed")
    @get:JvmName("isClosed")
    public val isClosed: Boolean,
) {
    public companion object
}
