// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("premiumStatePaymentOption")
@TLCombinatorId(0x7D06B579)
public data class PremiumStatePaymentOption(
    @SerialName("payment_option")
    @get:JvmName("paymentOption")
    public val paymentOption: PremiumPaymentOption,
    @SerialName("is_current")
    @get:JvmName("isCurrent")
    public val isCurrent: Boolean,
    @SerialName("is_upgrade")
    @get:JvmName("isUpgrade")
    public val isUpgrade: Boolean,
    @SerialName("last_transaction_id")
    @get:JvmName("lastTransactionId")
    public val lastTransactionId: String,
) {
    public companion object
}
