// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("premiumGiveawayParameters")
@TLCombinatorId(0x7794FF39)
public data class PremiumGiveawayParameters(
    @SerialName("boosted_chat_id")
    @get:JvmName("boostedChatId")
    public val boostedChatId: Long,
    @SerialName("additional_chat_ids")
    @get:JvmName("additionalChatIds")
    public val additionalChatIds: List<Long>,
    @SerialName("winners_selection_date")
    @get:JvmName("winnersSelectionDate")
    public val winnersSelectionDate: Int,
    @SerialName("only_new_members")
    @get:JvmName("onlyNewMembers")
    public val onlyNewMembers: Boolean,
    @SerialName("country_codes")
    @get:JvmName("countryCodes")
    public val countryCodes: List<String>,
) {
    public companion object
}
