// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("premiumPaymentOption")
@TLCombinatorId(0x8C0C5FB2)
public data class PremiumPaymentOption(
    @get:JvmName("currency")
    public val currency: String,
    @get:JvmName("amount")
    public val amount: Long,
    @SerialName("discount_percentage")
    @get:JvmName("discountPercentage")
    public val discountPercentage: Int,
    @SerialName("month_count")
    @get:JvmName("monthCount")
    public val monthCount: Int,
    @SerialName("store_product_id")
    @get:JvmName("storeProductId")
    public val storeProductId: String,
    @SerialName("payment_link")
    @get:JvmName("paymentLink")
    public val paymentLink: InternalLinkType,
) {
    public companion object
}
