// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("premiumFeatures")
@TLCombinatorId(0x6FC4B43C)
public data class PremiumFeatures(
    @get:JvmName("features")
    public val features: List<PremiumFeature>,
    @get:JvmName("limits")
    public val limits: List<PremiumLimit>,
    @SerialName("payment_link")
    @get:JvmName("paymentLink")
    public val paymentLink: InternalLinkType,
) {
    public companion object
}
