// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface PremiumGiveawayInfo {
    @Serializable
    @SerialName("premiumGiveawayInfoOngoing")
    @TLCombinatorId(0x48D3CE6F)
    public data class PremiumGiveawayInfoOngoing(
        @SerialName("creation_date")
        @get:JvmName("creationDate")
        public val creationDate: Int,
        @get:JvmName("status")
        public val status: PremiumGiveawayParticipantStatus,
        @SerialName("is_ended")
        @get:JvmName("isEnded")
        public val isEnded: Boolean,
    ) : PremiumGiveawayInfo {
        public companion object
    }

    @Serializable
    @SerialName("premiumGiveawayInfoCompleted")
    @TLCombinatorId(0xFC8B501B)
    public data class PremiumGiveawayInfoCompleted(
        @SerialName("creation_date")
        @get:JvmName("creationDate")
        public val creationDate: Int,
        @SerialName("actual_winners_selection_date")
        @get:JvmName("actualWinnersSelectionDate")
        public val actualWinnersSelectionDate: Int,
        @SerialName("was_refunded")
        @get:JvmName("wasRefunded")
        public val wasRefunded: Boolean,
        @SerialName("winner_count")
        @get:JvmName("winnerCount")
        public val winnerCount: Int,
        @SerialName("activation_count")
        @get:JvmName("activationCount")
        public val activationCount: Int,
        @SerialName("gift_code")
        @get:JvmName("giftCode")
        public val giftCode: String,
    ) : PremiumGiveawayInfo {
        public companion object
    }

    public companion object
}
