// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("premiumGiftCodeInfo")
@TLCombinatorId(0xB88FA8DE)
public data class PremiumGiftCodeInfo(
    @SerialName("creator_id")
    @get:JvmName("creatorId")
    public val creatorId: MessageSender,
    @SerialName("creation_date")
    @get:JvmName("creationDate")
    public val creationDate: Int,
    @SerialName("is_from_giveaway")
    @get:JvmName("isFromGiveaway")
    public val isFromGiveaway: Boolean,
    @SerialName("giveaway_message_id")
    @get:JvmName("giveawayMessageId")
    public val giveawayMessageId: Long,
    @SerialName("month_count")
    @get:JvmName("monthCount")
    public val monthCount: Int,
    @SerialName("user_id")
    @get:JvmName("userId")
    public val userId: Long,
    @SerialName("use_date")
    @get:JvmName("useDate")
    public val useDate: Int,
) {
    public companion object
}
