// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("premiumGiftCodePaymentOptions")
@TLCombinatorId(0xBBF07F21)
public data class PremiumGiftCodePaymentOptions(
    @get:JvmName("options")
    public val options: List<PremiumGiftCodePaymentOption>,
) {
    public companion object
}
