// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("profilePhoto")
@TLCombinatorId(0xC2DC3C5E)
public data class ProfilePhoto(
    @get:JvmName("id")
    public val id: Long,
    @get:JvmName("small")
    public val small: File,
    @get:JvmName("big")
    public val big: File,
    @get:JvmName("minithumbnail")
    public val minithumbnail: Minithumbnail,
    @SerialName("has_animation")
    @get:JvmName("hasAnimation")
    public val hasAnimation: Boolean,
    @SerialName("is_personal")
    @get:JvmName("isPersonal")
    public val isPersonal: Boolean,
) {
    public companion object
}
