// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface ReactionType {
    @Serializable
    @SerialName("reactionTypeEmoji")
    @TLCombinatorId(0x8C3E22C8)
    public data class ReactionTypeEmoji(
        @get:JvmName("emoji")
        public val emoji: String,
    ) : ReactionType {
        public companion object
    }

    @Serializable
    @SerialName("reactionTypeCustomEmoji")
    @TLCombinatorId(0xC50B42F3)
    public data class ReactionTypeCustomEmoji(
        @SerialName("custom_emoji_id")
        @get:JvmName("customEmojiId")
        public val customEmojiId: Long,
    ) : ReactionType {
        public companion object
    }

    public companion object
}
