// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("recommendedChatFolder")
@TLCombinatorId(0x81D7B4B6)
public data class RecommendedChatFolder(
    @get:JvmName("folder")
    public val folder: ChatFolder,
    @get:JvmName("description")
    public val description: String,
) {
    public companion object
}
