// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("savedCredentials")
@TLCombinatorId(0xE9EE14DC)
public data class SavedCredentials(
    @get:JvmName("id")
    public val id: String,
    @get:JvmName("title")
    public val title: String,
) {
    public companion object
}
