// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("scopeAutosaveSettings")
@TLCombinatorId(0x5C329F33)
public data class ScopeAutosaveSettings(
    @SerialName("autosave_photos")
    @get:JvmName("autosavePhotos")
    public val autosavePhotos: Boolean,
    @SerialName("autosave_videos")
    @get:JvmName("autosaveVideos")
    public val autosaveVideos: Boolean,
    @SerialName("max_video_file_size")
    @get:JvmName("maxVideoFileSize")
    public val maxVideoFileSize: Long,
) {
    public companion object
}
