// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("seconds")
@TLCombinatorId(0x3936E58E)
public data class Seconds(
    @get:JvmName("seconds")
    public val seconds: Double,
) {
    public companion object
}
