// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class SecretChatState {
    @SerialName("secretChatStatePending")
    @TLCombinatorId(0x9E6C967C)
    SECRET_CHAT_STATE_PENDING,
    @SerialName("secretChatStateReady")
    @TLCombinatorId(0x9FF4B7E9)
    SECRET_CHAT_STATE_READY,
    @SerialName("secretChatStateClosed")
    @TLCombinatorId(0x8C1006ED)
    SECRET_CHAT_STATE_CLOSED,
    ;

    public companion object
}
