// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("sessions")
@TLCombinatorId(0x323DD212)
public data class Sessions(
    @get:JvmName("sessions")
    public val sessions: List<Session>,
    @SerialName("inactive_session_ttl_days")
    @get:JvmName("inactiveSessionTtlDays")
    public val inactiveSessionTtlDays: Int,
) {
    public companion object
}
