// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface SpeechRecognitionResult {
    @Serializable
    @SerialName("speechRecognitionResultPending")
    @TLCombinatorId(0x9EBC8E00)
    public data class SpeechRecognitionResultPending(
        @SerialName("partial_text")
        @get:JvmName("partialText")
        public val partialText: String,
    ) : SpeechRecognitionResult {
        public companion object
    }

    @Serializable
    @SerialName("speechRecognitionResultText")
    @TLCombinatorId(0x80E681DD)
    public data class SpeechRecognitionResultText(
        @get:JvmName("text")
        public val text: String,
    ) : SpeechRecognitionResult {
        public companion object
    }

    @Serializable
    @SerialName("speechRecognitionResultError")
    @TLCombinatorId(0x09D243FC)
    public data class SpeechRecognitionResultError(
        @get:JvmName("error")
        public val error: Error,
    ) : SpeechRecognitionResult {
        public companion object
    }

    public companion object
}
