// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class StickerType {
    @SerialName("stickerTypeRegular")
    @TLCombinatorId(0x035BC575)
    STICKER_TYPE_REGULAR,
    @SerialName("stickerTypeMask")
    @TLCombinatorId(0x96C63694)
    STICKER_TYPE_MASK,
    @SerialName("stickerTypeCustomEmoji")
    @TLCombinatorId(0xF8CD7787)
    STICKER_TYPE_CUSTOM_EMOJI,
    ;

    public companion object
}
