// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("stickers")
@TLCombinatorId(0x75B5F5FC)
public data class Stickers(
    @get:JvmName("stickers")
    public val stickers: List<Sticker>,
) {
    public companion object
}
