// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("storyInfo")
@TLCombinatorId(0x8997C352)
public data class StoryInfo(
    @SerialName("story_id")
    @get:JvmName("storyId")
    public val storyId: Int,
    @get:JvmName("date")
    public val date: Int,
    @SerialName("is_for_close_friends")
    @get:JvmName("isForCloseFriends")
    public val isForCloseFriends: Boolean,
) {
    public companion object
}
