// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface StoryPrivacySettings {
    @Serializable
    @SerialName("storyPrivacySettingsEveryone")
    @TLCombinatorId(0x35194263)
    public data class StoryPrivacySettingsEveryone(
        @SerialName("except_user_ids")
        @get:JvmName("exceptUserIds")
        public val exceptUserIds: List<Long>,
    ) : StoryPrivacySettings {
        public companion object
    }

    @Serializable
    @SerialName("storyPrivacySettingsContacts")
    @TLCombinatorId(0x02FF4AFD)
    public data class StoryPrivacySettingsContacts(
        @SerialName("except_user_ids")
        @get:JvmName("exceptUserIds")
        public val exceptUserIds: List<Long>,
    ) : StoryPrivacySettings {
        public companion object
    }

    @Serializable
    @SerialName("storyPrivacySettingsCloseFriends")
    @TLCombinatorId(0x7CFF8B60)
    public object StoryPrivacySettingsCloseFriends : StoryPrivacySettings

    @Serializable
    @SerialName("storyPrivacySettingsSelectedUsers")
    @TLCombinatorId(0x8F9964C6)
    public data class StoryPrivacySettingsSelectedUsers(
        @SerialName("user_ids")
        @get:JvmName("userIds")
        public val userIds: List<Long>,
    ) : StoryPrivacySettings {
        public companion object
    }

    public companion object
}
