// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("storyViewers")
@TLCombinatorId(0x36D999CF)
public data class StoryViewers(
    @SerialName("total_count")
    @get:JvmName("totalCount")
    public val totalCount: Int,
    @SerialName("total_reaction_count")
    @get:JvmName("totalReactionCount")
    public val totalReactionCount: Int,
    @get:JvmName("viewers")
    public val viewers: List<StoryViewer>,
    @SerialName("next_offset")
    @get:JvmName("nextOffset")
    public val nextOffset: String,
) {
    public companion object
}
