// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class StoryList {
    @SerialName("storyListMain")
    @TLCombinatorId(0xD7EEB3FF)
    STORY_LIST_MAIN,
    @SerialName("storyListArchive")
    @TLCombinatorId(0xFD80A741)
    STORY_LIST_ARCHIVE,
    ;

    public companion object
}
