// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface StorePaymentPurpose {
    @Serializable
    @SerialName("storePaymentPurposePremiumSubscription")
    @TLCombinatorId(0x4B558114)
    public data class StorePaymentPurposePremiumSubscription(
        @SerialName("is_restore")
        @get:JvmName("isRestore")
        public val isRestore: Boolean,
        @SerialName("is_upgrade")
        @get:JvmName("isUpgrade")
        public val isUpgrade: Boolean,
    ) : StorePaymentPurpose {
        public companion object
    }

    @Serializable
    @SerialName("storePaymentPurposeGiftedPremium")
    @TLCombinatorId(0x7240C0D1)
    public data class StorePaymentPurposeGiftedPremium(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("currency")
        public val currency: String,
        @get:JvmName("amount")
        public val amount: Long,
    ) : StorePaymentPurpose {
        public companion object
    }

    @Serializable
    @SerialName("storePaymentPurposePremiumGiftCodes")
    @TLCombinatorId(0xA4EEFFE2)
    public data class StorePaymentPurposePremiumGiftCodes(
        @SerialName("boosted_chat_id")
        @get:JvmName("boostedChatId")
        public val boostedChatId: Long,
        @get:JvmName("currency")
        public val currency: String,
        @get:JvmName("amount")
        public val amount: Long,
        @SerialName("user_ids")
        @get:JvmName("userIds")
        public val userIds: List<Long>,
    ) : StorePaymentPurpose {
        public companion object
    }

    @Serializable
    @SerialName("storePaymentPurposePremiumGiveaway")
    @TLCombinatorId(0x504790D9)
    public data class StorePaymentPurposePremiumGiveaway(
        @get:JvmName("parameters")
        public val parameters: PremiumGiveawayParameters,
        @get:JvmName("currency")
        public val currency: String,
        @get:JvmName("amount")
        public val amount: Long,
    ) : StorePaymentPurpose {
        public companion object
    }

    public companion object
}
