// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("supergroup")
@TLCombinatorId(0x8B30B3C5)
public data class Supergroup(
    @get:JvmName("id")
    public val id: Long,
    @get:JvmName("usernames")
    public val usernames: Usernames,
    @get:JvmName("date")
    public val date: Int,
    @get:JvmName("status")
    public val status: ChatMemberStatus,
    @SerialName("member_count")
    @get:JvmName("memberCount")
    public val memberCount: Int,
    @SerialName("has_linked_chat")
    @get:JvmName("hasLinkedChat")
    public val hasLinkedChat: Boolean,
    @SerialName("has_location")
    @get:JvmName("hasLocation")
    public val hasLocation: Boolean,
    @SerialName("sign_messages")
    @get:JvmName("signMessages")
    public val signMessages: Boolean,
    @SerialName("join_to_send_messages")
    @get:JvmName("joinToSendMessages")
    public val joinToSendMessages: Boolean,
    @SerialName("join_by_request")
    @get:JvmName("joinByRequest")
    public val joinByRequest: Boolean,
    @SerialName("is_slow_mode_enabled")
    @get:JvmName("isSlowModeEnabled")
    public val isSlowModeEnabled: Boolean,
    @SerialName("is_channel")
    @get:JvmName("isChannel")
    public val isChannel: Boolean,
    @SerialName("is_broadcast_group")
    @get:JvmName("isBroadcastGroup")
    public val isBroadcastGroup: Boolean,
    @SerialName("is_forum")
    @get:JvmName("isForum")
    public val isForum: Boolean,
    @SerialName("is_verified")
    @get:JvmName("isVerified")
    public val isVerified: Boolean,
    @SerialName("restriction_reason")
    @get:JvmName("restrictionReason")
    public val restrictionReason: String,
    @SerialName("is_scam")
    @get:JvmName("isScam")
    public val isScam: Boolean,
    @SerialName("is_fake")
    @get:JvmName("isFake")
    public val isFake: Boolean,
    @SerialName("has_active_stories")
    @get:JvmName("hasActiveStories")
    public val hasActiveStories: Boolean,
    @SerialName("has_unread_active_stories")
    @get:JvmName("hasUnreadActiveStories")
    public val hasUnreadActiveStories: Boolean,
) {
    public companion object
}
