// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface TargetChat {
    @Serializable
    @SerialName("targetChatCurrent")
    @TLCombinatorId(0xE729D110)
    public object TargetChatCurrent : TargetChat

    @Serializable
    @SerialName("targetChatChosen")
    @TLCombinatorId(0xEDACCAD2)
    public data class TargetChatChosen(
        @SerialName("allow_user_chats")
        @get:JvmName("allowUserChats")
        public val allowUserChats: Boolean,
        @SerialName("allow_bot_chats")
        @get:JvmName("allowBotChats")
        public val allowBotChats: Boolean,
        @SerialName("allow_group_chats")
        @get:JvmName("allowGroupChats")
        public val allowGroupChats: Boolean,
        @SerialName("allow_channel_chats")
        @get:JvmName("allowChannelChats")
        public val allowChannelChats: Boolean,
    ) : TargetChat {
        public companion object
    }

    @Serializable
    @SerialName("targetChatInternalLink")
    @TLCombinatorId(0xDD788FE0)
    public data class TargetChatInternalLink(
        @get:JvmName("link")
        public val link: InternalLinkType,
    ) : TargetChat {
        public companion object
    }

    public companion object
}
