// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class ThumbnailFormat {
    @SerialName("thumbnailFormatJpeg")
    @TLCombinatorId(0xD90C5488)
    THUMBNAIL_FORMAT_JPEG,
    @SerialName("thumbnailFormatGif")
    @TLCombinatorId(0x4AA3258A)
    THUMBNAIL_FORMAT_GIF,
    @SerialName("thumbnailFormatMpeg4")
    @TLCombinatorId(0x109B57FE)
    THUMBNAIL_FORMAT_MPEG4,
    @SerialName("thumbnailFormatPng")
    @TLCombinatorId(0x5E0697F5)
    THUMBNAIL_FORMAT_PNG,
    @SerialName("thumbnailFormatTgs")
    @TLCombinatorId(0x4E694852)
    THUMBNAIL_FORMAT_TGS,
    @SerialName("thumbnailFormatWebm")
    @TLCombinatorId(0xD8A7E727)
    THUMBNAIL_FORMAT_WEBM,
    @SerialName("thumbnailFormatWebp")
    @TLCombinatorId(0xFCCE4C12)
    THUMBNAIL_FORMAT_WEBP,
    ;

    public companion object
}
