// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class TopChatCategory {
    @SerialName("topChatCategoryUsers")
    @TLCombinatorId(0x3D324D80)
    TOP_CHAT_CATEGORY_USERS,
    @SerialName("topChatCategoryBots")
    @TLCombinatorId(0xA1FEEB15)
    TOP_CHAT_CATEGORY_BOTS,
    @SerialName("topChatCategoryGroups")
    @TLCombinatorId(0x5B32D08E)
    TOP_CHAT_CATEGORY_GROUPS,
    @SerialName("topChatCategoryChannels")
    @TLCombinatorId(0xE22600E3)
    TOP_CHAT_CATEGORY_CHANNELS,
    @SerialName("topChatCategoryInlineBots")
    @TLCombinatorId(0x1678EB7C)
    TOP_CHAT_CATEGORY_INLINE_BOTS,
    @SerialName("topChatCategoryCalls")
    @TLCombinatorId(0x153B50DD)
    TOP_CHAT_CATEGORY_CALLS,
    @SerialName("topChatCategoryForwardChats")
    @TLCombinatorId(0x6515B7D5)
    TOP_CHAT_CATEGORY_FORWARD_CHATS,
    ;

    public companion object
}
