// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("userFullInfo")
@TLCombinatorId(0xCDC395AD)
public data class UserFullInfo(
    @SerialName("personal_photo")
    @get:JvmName("personalPhoto")
    public val personalPhoto: ChatPhoto,
    @get:JvmName("photo")
    public val photo: ChatPhoto,
    @SerialName("public_photo")
    @get:JvmName("publicPhoto")
    public val publicPhoto: ChatPhoto,
    @SerialName("block_list")
    @get:JvmName("blockList")
    public val blockList: BlockList,
    @SerialName("can_be_called")
    @get:JvmName("canBeCalled")
    public val canBeCalled: Boolean,
    @SerialName("supports_video_calls")
    @get:JvmName("supportsVideoCalls")
    public val supportsVideoCalls: Boolean,
    @SerialName("has_private_calls")
    @get:JvmName("hasPrivateCalls")
    public val hasPrivateCalls: Boolean,
    @SerialName("has_private_forwards")
    @get:JvmName("hasPrivateForwards")
    public val hasPrivateForwards: Boolean,
    @SerialName("has_restricted_voice_and_video_note_messages")
    @get:JvmName("hasRestrictedVoiceAndVideoNoteMessages")
    public val hasRestrictedVoiceAndVideoNoteMessages: Boolean,
    @SerialName("has_pinned_stories")
    @get:JvmName("hasPinnedStories")
    public val hasPinnedStories: Boolean,
    @SerialName("need_phone_number_privacy_exception")
    @get:JvmName("needPhoneNumberPrivacyException")
    public val needPhoneNumberPrivacyException: Boolean,
    @get:JvmName("bio")
    public val bio: FormattedText,
    @SerialName("premium_gift_options")
    @get:JvmName("premiumGiftOptions")
    public val premiumGiftOptions: List<PremiumPaymentOption>,
    @SerialName("group_in_common_count")
    @get:JvmName("groupInCommonCount")
    public val groupInCommonCount: Int,
    @SerialName("bot_info")
    @get:JvmName("botInfo")
    public val botInfo: BotInfo,
) {
    public companion object
}
