// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface UserType {
    @Serializable
    @SerialName("userTypeRegular")
    @TLCombinatorId(0xDC51699B)
    public object UserTypeRegular : UserType

    @Serializable
    @SerialName("userTypeDeleted")
    @TLCombinatorId(0x94403D24)
    public object UserTypeDeleted : UserType

    @Serializable
    @SerialName("userTypeBot")
    @TLCombinatorId(0xF979E790)
    public data class UserTypeBot(
        @SerialName("can_be_edited")
        @get:JvmName("canBeEdited")
        public val canBeEdited: Boolean,
        @SerialName("can_join_groups")
        @get:JvmName("canJoinGroups")
        public val canJoinGroups: Boolean,
        @SerialName("can_read_all_group_messages")
        @get:JvmName("canReadAllGroupMessages")
        public val canReadAllGroupMessages: Boolean,
        @SerialName("is_inline")
        @get:JvmName("isInline")
        public val isInline: Boolean,
        @SerialName("inline_query_placeholder")
        @get:JvmName("inlineQueryPlaceholder")
        public val inlineQueryPlaceholder: String,
        @SerialName("need_location")
        @get:JvmName("needLocation")
        public val needLocation: Boolean,
        @SerialName("can_be_added_to_attachment_menu")
        @get:JvmName("canBeAddedToAttachmentMenu")
        public val canBeAddedToAttachmentMenu: Boolean,
    ) : UserType {
        public companion object
    }

    @Serializable
    @SerialName("userTypeUnknown")
    @TLCombinatorId(0xD4D0613D)
    public object UserTypeUnknown : UserType

    public companion object
}
