// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class UserPrivacySetting {
    @SerialName("userPrivacySettingShowStatus")
    @TLCombinatorId(0x6F0884FE)
    USER_PRIVACY_SETTING_SHOW_STATUS,
    @SerialName("userPrivacySettingShowProfilePhoto")
    @TLCombinatorId(0x53F3C9F5)
    USER_PRIVACY_SETTING_SHOW_PROFILE_PHOTO,
    @SerialName("userPrivacySettingShowLinkInForwardedMessages")
    @TLCombinatorId(0x2353B6E6)
    USER_PRIVACY_SETTING_SHOW_LINK_IN_FORWARDED_MESSAGES,
    @SerialName("userPrivacySettingShowPhoneNumber")
    @TLCombinatorId(0xD0D1A229)
    USER_PRIVACY_SETTING_SHOW_PHONE_NUMBER,
    @SerialName("userPrivacySettingShowBio")
    @TLCombinatorId(0x39382761)
    USER_PRIVACY_SETTING_SHOW_BIO,
    @SerialName("userPrivacySettingAllowChatInvites")
    @TLCombinatorId(0x4BCC1D27)
    USER_PRIVACY_SETTING_ALLOW_CHAT_INVITES,
    @SerialName("userPrivacySettingAllowCalls")
    @TLCombinatorId(0xC9F0C705)
    USER_PRIVACY_SETTING_ALLOW_CALLS,
    @SerialName("userPrivacySettingAllowPeerToPeerCalls")
    @TLCombinatorId(0x1502B940)
    USER_PRIVACY_SETTING_ALLOW_PEER_TO_PEER_CALLS,
    @SerialName("userPrivacySettingAllowFindingByPhoneNumber")
    @TLCombinatorId(0x91EE6D51)
    USER_PRIVACY_SETTING_ALLOW_FINDING_BY_PHONE_NUMBER,
    @SerialName("userPrivacySettingAllowPrivateVoiceAndVideoNoteMessages")
    @TLCombinatorId(0x14272E3C)
    USER_PRIVACY_SETTING_ALLOW_PRIVATE_VOICE_AND_VIDEO_NOTE_MESSAGES,
    ;

    public companion object
}
