// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("webAppInfo")
@TLCombinatorId(0x2EFDB2E8)
public data class WebAppInfo(
    @SerialName("launch_id")
    @get:JvmName("launchId")
    public val launchId: Long,
    @get:JvmName("url")
    public val url: String,
) {
    public companion object
}
