// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.td

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("webPageInstantView")
@TLCombinatorId(0x2E626D55)
public data class WebPageInstantView(
    @SerialName("page_blocks")
    @get:JvmName("pageBlocks")
    public val pageBlocks: List<PageBlock>,
    @SerialName("view_count")
    @get:JvmName("viewCount")
    public val viewCount: Int,
    @get:JvmName("version")
    public val version: Int,
    @SerialName("is_rtl")
    @get:JvmName("isRtl")
    public val isRtl: Boolean,
    @SerialName("is_full")
    @get:JvmName("isFull")
    public val isFull: Boolean,
    @SerialName("feedback_link")
    @get:JvmName("feedbackLink")
    public val feedbackLink: InternalLinkType,
) {
    public companion object
}
