// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.storage.db.key

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("storage.db.key.torrentMeta")
@TLCombinatorId(0x62239D66)
public data class StorageDbKeyTorrentMeta(
    @TLFixedSize(value = 32)
    @get:JvmName("hash")
    public val hash: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
