// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.tls

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("tls.arg")
@TLCombinatorId(0x29DFE61B)
public data class TlsArg(
    @get:JvmName("id")
    public val id: String,
    @get:JvmName("flags")
    public val flags: Int,
    @SerialName("var_num")
    @TLConditional("flags", 1)
    @get:JvmName("varNum")
    public val varNum: Int? = null,
    @SerialName("exist_var_num")
    @TLConditional("flags", 2)
    @get:JvmName("existVarNum")
    public val existVarNum: Int? = null,
    @SerialName("exist_var_bit")
    @TLConditional("flags", 2)
    @get:JvmName("existVarBit")
    public val existVarBit: Int? = null,
    @get:JvmName("type")
    public val type: TlsTypeExpr,
) {
    public companion object
}
