// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.tls

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("tls.combinator")
@TLCombinatorId(0x5C0A1ED5)
public data class TlsCombinator(
    @get:JvmName("name")
    public val name: Int,
    @get:JvmName("id")
    public val id: String,
    @SerialName("type_name")
    @get:JvmName("typeName")
    public val typeName: Int,
    @get:JvmName("left")
    public val left: TlsCombinatorLeft,
    @get:JvmName("right")
    public val right: TlsCombinatorRight,
) {
    public companion object
}
