// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.validatorsession

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("validatorSession.statsRound")
@TLCombinatorId(0xA32FDF66)
public data class ValidatorSessionStatsRound(
    @get:JvmName("timestamp")
    public val timestamp: Long,
    @get:JvmName("producers")
    public val producers: List<ValidatorSessionStatsProducer>,
) {
    public companion object
}
