// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.validatorsession

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("validatorSession.candidate")
@TLCombinatorId(0x7D337845)
public data class ValidatorSessionCandidate(
    @TLFixedSize(value = 32)
    @get:JvmName("src")
    public val src: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("round")
    public val round: Int,
    @SerialName("root_hash")
    @TLFixedSize(value = 32)
    @get:JvmName("rootHash")
    public val rootHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("data")
    public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @SerialName("collated_data")
    @get:JvmName("collatedData")
    public val collatedData: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
