// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.validatorsession

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.tonnode.TonNodeBlockId

@Serializable
@SerialName("validatorSession.stats")
@TLCombinatorId(0x684D5A8F)
public data class ValidatorSessionStats(
    @get:JvmName("id")
    public val id: TonNodeBlockId,
    @get:JvmName("timestamp")
    public val timestamp: Long,
    @TLFixedSize(value = 32)
    @get:JvmName("self")
    public val self: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @TLFixedSize(value = 32)
    @get:JvmName("creator")
    public val creator: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @SerialName("total_validators")
    @get:JvmName("totalValidators")
    public val totalValidators: Int,
    @SerialName("total_weight")
    @get:JvmName("totalWeight")
    public val totalWeight: Long,
    @get:JvmName("signatures")
    public val signatures: Int,
    @SerialName("signatures_weight")
    @get:JvmName("signaturesWeight")
    public val signaturesWeight: Long,
    @SerialName("approve_signatures")
    @get:JvmName("approveSignatures")
    public val approveSignatures: Int,
    @SerialName("approve_signatures_weight")
    @get:JvmName("approveSignaturesWeight")
    public val approveSignaturesWeight: Long,
    @SerialName("first_round")
    @get:JvmName("firstRound")
    public val firstRound: Int,
    @get:JvmName("rounds")
    public val rounds: List<ValidatorSessionStatsRound>,
) {
    public companion object
}
