// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.tonlib

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("exportedPemKey")
@TLCombinatorId(0x54F700BD)
public data class ExportedPemKey(
    @get:JvmName("pem")
    public val pem: String,
) {
    public companion object
}
