// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.tonlib

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface SyncState {
    @Serializable
    @SerialName("syncStateDone")
    @TLCombinatorId(0x53F33909)
    public object SyncStateDone : SyncState

    @Serializable
    @SerialName("syncStateInProgress")
    @TLCombinatorId(0x066BC4C7)
    public data class SyncStateInProgress(
        @SerialName("from_seqno")
        @get:JvmName("fromSeqno")
        public val fromSeqno: Int,
        @SerialName("to_seqno")
        @get:JvmName("toSeqno")
        public val toSeqno: Int,
        @SerialName("current_seqno")
        @get:JvmName("currentSeqno")
        public val currentSeqno: Int,
    ) : SyncState {
        public companion object
    }

    public companion object
}
