// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("authorization")
@TLCombinatorId(0xAD01D61D)
public data class Authorization(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("current")
    public val current: Unit? = null,
    @SerialName("official_app")
    @TLConditional("flags", 1)
    @get:JvmName("officialApp")
    public val officialApp: Unit? = null,
    @SerialName("password_pending")
    @TLConditional("flags", 2)
    @get:JvmName("passwordPending")
    public val passwordPending: Unit? = null,
    @SerialName("encrypted_requests_disabled")
    @TLConditional("flags", 3)
    @get:JvmName("encryptedRequestsDisabled")
    public val encryptedRequestsDisabled: Unit? = null,
    @SerialName("call_requests_disabled")
    @TLConditional("flags", 4)
    @get:JvmName("callRequestsDisabled")
    public val callRequestsDisabled: Unit? = null,
    @TLConditional("flags", 5)
    @get:JvmName("unconfirmed")
    public val unconfirmed: Unit? = null,
    @get:JvmName("hash")
    public val hash: Long,
    @SerialName("device_model")
    @get:JvmName("deviceModel")
    public val deviceModel: String,
    @get:JvmName("platform")
    public val platform: String,
    @SerialName("system_version")
    @get:JvmName("systemVersion")
    public val systemVersion: String,
    @SerialName("api_id")
    @get:JvmName("apiId")
    public val apiId: Int,
    @SerialName("app_name")
    @get:JvmName("appName")
    public val appName: String,
    @SerialName("app_version")
    @get:JvmName("appVersion")
    public val appVersion: String,
    @SerialName("date_created")
    @get:JvmName("dateCreated")
    public val dateCreated: Int,
    @SerialName("date_active")
    @get:JvmName("dateActive")
    public val dateActive: Int,
    @get:JvmName("ip")
    public val ip: String,
    @get:JvmName("country")
    public val country: String,
    @get:JvmName("region")
    public val region: String,
) {
    public companion object
}
