// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("autoDownloadSettings")
@TLCombinatorId(0xBAA57628)
public data class AutoDownloadSettings(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("disabled")
    public val disabled: Unit? = null,
    @SerialName("video_preload_large")
    @TLConditional("flags", 1)
    @get:JvmName("videoPreloadLarge")
    public val videoPreloadLarge: Unit? = null,
    @SerialName("audio_preload_next")
    @TLConditional("flags", 2)
    @get:JvmName("audioPreloadNext")
    public val audioPreloadNext: Unit? = null,
    @SerialName("phonecalls_less_data")
    @TLConditional("flags", 3)
    @get:JvmName("phonecallsLessData")
    public val phonecallsLessData: Unit? = null,
    @SerialName("stories_preload")
    @TLConditional("flags", 4)
    @get:JvmName("storiesPreload")
    public val storiesPreload: Unit? = null,
    @SerialName("photo_size_max")
    @get:JvmName("photoSizeMax")
    public val photoSizeMax: Int,
    @SerialName("video_size_max")
    @get:JvmName("videoSizeMax")
    public val videoSizeMax: Long,
    @SerialName("file_size_max")
    @get:JvmName("fileSizeMax")
    public val fileSizeMax: Long,
    @SerialName("video_upload_maxbitrate")
    @get:JvmName("videoUploadMaxbitrate")
    public val videoUploadMaxbitrate: Int,
    @SerialName("small_queue_active_operations_max")
    @get:JvmName("smallQueueActiveOperationsMax")
    public val smallQueueActiveOperationsMax: Int,
    @SerialName("large_queue_active_operations_max")
    @get:JvmName("largeQueueActiveOperationsMax")
    public val largeQueueActiveOperationsMax: Int,
) {
    public companion object
}
