// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("botCommand")
@TLCombinatorId(0xC27AC8C7)
public data class BotCommand(
    @get:JvmName("command")
    public val command: String,
    @get:JvmName("description")
    public val description: String,
) {
    public companion object
}
