// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("cdnConfig")
@TLCombinatorId(0x5725E40A)
public data class CdnConfig(
    @SerialName("public_keys")
    @get:JvmName("publicKeys")
    public val publicKeys: List<CdnPublicKey>,
) {
    public companion object
}
