// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("chatAdminWithInvites")
@TLCombinatorId(0xF2ECEF23)
public data class ChatAdminWithInvites(
    @SerialName("admin_id")
    @get:JvmName("adminId")
    public val adminId: Long,
    @SerialName("invites_count")
    @get:JvmName("invitesCount")
    public val invitesCount: Int,
    @SerialName("revoked_invites_count")
    @get:JvmName("revokedInvitesCount")
    public val revokedInvitesCount: Int,
) {
    public companion object
}
