// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface DialogPeer {
    @Serializable
    @SerialName("dialogPeer")
    @TLCombinatorId(0xE56DBF05)
    public data class DialogPeer(
        @get:JvmName("peer")
        public val peer: Peer,
    ) : tl.telegram.DialogPeer {
        public companion object
    }

    @Serializable
    @SerialName("dialogPeerFolder")
    @TLCombinatorId(0x514519E2)
    public data class DialogPeerFolder(
        @SerialName("folder_id")
        @get:JvmName("folderId")
        public val folderId: Int,
    ) : tl.telegram.DialogPeer {
        public companion object
    }

    public companion object
}
