// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface EmojiList {
    @Serializable
    @SerialName("emojiListNotModified")
    @TLCombinatorId(0x481EADFA)
    public object EmojiListNotModified : tl.telegram.EmojiList

    @Serializable
    @SerialName("emojiList")
    @TLCombinatorId(0x7A1E11D1)
    public data class EmojiList(
        @get:JvmName("hash")
        public val hash: Long,
        @SerialName("document_id")
        @get:JvmName("documentId")
        public val documentId: List<Long>,
    ) : tl.telegram.EmojiList {
        public companion object
    }

    public companion object
}
