// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface EmojiKeyword {
    @Serializable
    @SerialName("emojiKeyword")
    @TLCombinatorId(0xD5B3B9F9)
    public data class EmojiKeyword(
        @get:JvmName("keyword")
        public val keyword: String,
        @get:JvmName("emoticons")
        public val emoticons: List<String>,
    ) : tl.telegram.EmojiKeyword {
        public companion object
    }

    @Serializable
    @SerialName("emojiKeywordDeleted")
    @TLCombinatorId(0x236DF622)
    public data class EmojiKeywordDeleted(
        @get:JvmName("keyword")
        public val keyword: String,
        @get:JvmName("emoticons")
        public val emoticons: List<String>,
    ) : tl.telegram.EmojiKeyword {
        public companion object
    }

    public companion object
}
