// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface GeoPoint {
    @Serializable
    @SerialName("geoPointEmpty")
    @TLCombinatorId(0x1117DD5F)
    public object GeoPointEmpty : tl.telegram.GeoPoint

    @Serializable
    @SerialName("geoPoint")
    @TLCombinatorId(0xB2A2F663)
    public data class GeoPoint(
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("long")
        public val long: Double,
        @get:JvmName("lat")
        public val lat: Double,
        @SerialName("access_hash")
        @get:JvmName("accessHash")
        public val accessHash: Long,
        @SerialName("accuracy_radius")
        @TLConditional("flags", 0)
        @get:JvmName("accuracyRadius")
        public val accuracyRadius: Int? = null,
    ) : tl.telegram.GeoPoint {
        public companion object
    }

    public companion object
}
