// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("groupCallParticipant")
@TLCombinatorId(0xEBA636FE)
public data class GroupCallParticipant(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("muted")
    public val muted: Unit? = null,
    @TLConditional("flags", 1)
    @get:JvmName("left")
    public val left: Unit? = null,
    @SerialName("can_self_unmute")
    @TLConditional("flags", 2)
    @get:JvmName("canSelfUnmute")
    public val canSelfUnmute: Unit? = null,
    @SerialName("just_joined")
    @TLConditional("flags", 4)
    @get:JvmName("justJoined")
    public val justJoined: Unit? = null,
    @TLConditional("flags", 5)
    @get:JvmName("versioned")
    public val versioned: Unit? = null,
    @TLConditional("flags", 8)
    @get:JvmName("min")
    public val min: Unit? = null,
    @SerialName("muted_by_you")
    @TLConditional("flags", 9)
    @get:JvmName("mutedByYou")
    public val mutedByYou: Unit? = null,
    @SerialName("volume_by_admin")
    @TLConditional("flags", 10)
    @get:JvmName("volumeByAdmin")
    public val volumeByAdmin: Unit? = null,
    @TLConditional("flags", 12)
    @get:JvmName("self")
    public val self: Unit? = null,
    @SerialName("video_joined")
    @TLConditional("flags", 15)
    @get:JvmName("videoJoined")
    public val videoJoined: Unit? = null,
    @get:JvmName("peer")
    public val peer: Peer,
    @get:JvmName("date")
    public val date: Int,
    @SerialName("active_date")
    @TLConditional("flags", 3)
    @get:JvmName("activeDate")
    public val activeDate: Int? = null,
    @get:JvmName("source")
    public val source: Int,
    @TLConditional("flags", 7)
    @get:JvmName("volume")
    public val volume: Int? = null,
    @TLConditional("flags", 11)
    @get:JvmName("about")
    public val about: String? = null,
    @SerialName("raise_hand_rating")
    @TLConditional("flags", 13)
    @get:JvmName("raiseHandRating")
    public val raiseHandRating: Long? = null,
    @TLConditional("flags", 6)
    @get:JvmName("video")
    public val video: GroupCallParticipantVideo? = null,
    @TLConditional("flags", 14)
    @get:JvmName("presentation")
    public val presentation: GroupCallParticipantVideo? = null,
) {
    public companion object
}
