// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("importedContact")
@TLCombinatorId(0xC13E3C50)
public data class ImportedContact(
    @SerialName("user_id")
    @get:JvmName("userId")
    public val userId: Long,
    @SerialName("client_id")
    @get:JvmName("clientId")
    public val clientId: Long,
) {
    public companion object
}
