// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class InlineQueryPeerType {
    @SerialName("inlineQueryPeerTypeSameBotPM")
    @TLCombinatorId(0x3081ED9D)
    INLINE_QUERY_PEER_TYPE_SAME_BOT_PM,
    @SerialName("inlineQueryPeerTypePM")
    @TLCombinatorId(0x833C0FAC)
    INLINE_QUERY_PEER_TYPE_PM,
    @SerialName("inlineQueryPeerTypeChat")
    @TLCombinatorId(0xD766C50A)
    INLINE_QUERY_PEER_TYPE_CHAT,
    @SerialName("inlineQueryPeerTypeMegagroup")
    @TLCombinatorId(0x5EC4BE43)
    INLINE_QUERY_PEER_TYPE_MEGAGROUP,
    @SerialName("inlineQueryPeerTypeBroadcast")
    @TLCombinatorId(0x6334EE9A)
    INLINE_QUERY_PEER_TYPE_BROADCAST,
    @SerialName("inlineQueryPeerTypeBotPM")
    @TLCombinatorId(0xE3B2D0C)
    INLINE_QUERY_PEER_TYPE_BOT_PM,
    ;

    public companion object
}
