// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface InputBotInlineResult {
    @Serializable
    @SerialName("inputBotInlineResult")
    @TLCombinatorId(0x88BF9319)
    public data class InputBotInlineResult(
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("id")
        public val id: String,
        @get:JvmName("type")
        public val type: String,
        @TLConditional("flags", 1)
        @get:JvmName("title")
        public val title: String? = null,
        @TLConditional("flags", 2)
        @get:JvmName("description")
        public val description: String? = null,
        @TLConditional("flags", 3)
        @get:JvmName("url")
        public val url: String? = null,
        @TLConditional("flags", 4)
        @get:JvmName("thumb")
        public val thumb: InputWebDocument? = null,
        @TLConditional("flags", 5)
        @get:JvmName("content")
        public val content: InputWebDocument? = null,
        @SerialName("send_message")
        @get:JvmName("sendMessage")
        public val sendMessage: InputBotInlineMessage,
    ) : tl.telegram.InputBotInlineResult {
        public companion object
    }

    @Serializable
    @SerialName("inputBotInlineResultPhoto")
    @TLCombinatorId(0xA8D864A7)
    public data class InputBotInlineResultPhoto(
        @get:JvmName("id")
        public val id: String,
        @get:JvmName("type")
        public val type: String,
        @get:JvmName("photo")
        public val photo: InputPhoto,
        @SerialName("send_message")
        @get:JvmName("sendMessage")
        public val sendMessage: InputBotInlineMessage,
    ) : tl.telegram.InputBotInlineResult {
        public companion object
    }

    @Serializable
    @SerialName("inputBotInlineResultDocument")
    @TLCombinatorId(0xFFF8FDC4)
    public data class InputBotInlineResultDocument(
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("id")
        public val id: String,
        @get:JvmName("type")
        public val type: String,
        @TLConditional("flags", 1)
        @get:JvmName("title")
        public val title: String? = null,
        @TLConditional("flags", 2)
        @get:JvmName("description")
        public val description: String? = null,
        @get:JvmName("document")
        public val document: InputDocument,
        @SerialName("send_message")
        @get:JvmName("sendMessage")
        public val sendMessage: InputBotInlineMessage,
    ) : tl.telegram.InputBotInlineResult {
        public companion object
    }

    @Serializable
    @SerialName("inputBotInlineResultGame")
    @TLCombinatorId(0x4FA417F2)
    public data class InputBotInlineResultGame(
        @get:JvmName("id")
        public val id: String,
        @SerialName("short_name")
        @get:JvmName("shortName")
        public val shortName: String,
        @SerialName("send_message")
        @get:JvmName("sendMessage")
        public val sendMessage: InputBotInlineMessage,
    ) : tl.telegram.InputBotInlineResult {
        public companion object
    }

    public companion object
}
