// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface InputPhoto {
    @Serializable
    @SerialName("inputPhotoEmpty")
    @TLCombinatorId(0x1CD7BF0D)
    public object InputPhotoEmpty : tl.telegram.InputPhoto

    @Serializable
    @SerialName("inputPhoto")
    @TLCombinatorId(0x3BB3B94A)
    public data class InputPhoto(
        @get:JvmName("id")
        public val id: Long,
        @SerialName("access_hash")
        @get:JvmName("accessHash")
        public val accessHash: Long,
        @SerialName("file_reference")
        @get:JvmName("fileReference")
        public val fileReference: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : tl.telegram.InputPhoto {
        public companion object
    }

    public companion object
}
