// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface InputDialogPeer {
    @Serializable
    @SerialName("inputDialogPeer")
    @TLCombinatorId(0xFCAAFEB7)
    public data class InputDialogPeer(
        @get:JvmName("peer")
        public val peer: InputPeer,
    ) : tl.telegram.InputDialogPeer {
        public companion object
    }

    @Serializable
    @SerialName("inputDialogPeerFolder")
    @TLCombinatorId(0x64600527)
    public data class InputDialogPeerFolder(
        @SerialName("folder_id")
        @get:JvmName("folderId")
        public val folderId: Int,
    ) : tl.telegram.InputDialogPeer {
        public companion object
    }

    public companion object
}
