// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("inputEncryptedChat")
@TLCombinatorId(0xF141B5E1)
public data class InputEncryptedChat(
    @SerialName("chat_id")
    @get:JvmName("chatId")
    public val chatId: Int,
    @SerialName("access_hash")
    @get:JvmName("accessHash")
    public val accessHash: Long,
) {
    public companion object
}
