// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface InputStickeredMedia {
    @Serializable
    @SerialName("inputStickeredMediaPhoto")
    @TLCombinatorId(0x4A992157)
    public data class InputStickeredMediaPhoto(
        @get:JvmName("id")
        public val id: InputPhoto,
    ) : InputStickeredMedia {
        public companion object
    }

    @Serializable
    @SerialName("inputStickeredMediaDocument")
    @TLCombinatorId(0x438865B)
    public data class InputStickeredMediaDocument(
        @get:JvmName("id")
        public val id: InputDocument,
    ) : InputStickeredMedia {
        public companion object
    }

    public companion object
}
