// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("inputPeerNotifySettings")
@TLCombinatorId(0xCACB6AE2)
public data class InputPeerNotifySettings(
    @get:JvmName("flags")
    public val flags: Int,
    @SerialName("show_previews")
    @TLConditional("flags", 0)
    @get:JvmName("showPreviews")
    public val showPreviews: Boolean? = null,
    @TLConditional("flags", 1)
    @get:JvmName("silent")
    public val silent: Boolean? = null,
    @SerialName("mute_until")
    @TLConditional("flags", 2)
    @get:JvmName("muteUntil")
    public val muteUntil: Int? = null,
    @TLConditional("flags", 3)
    @get:JvmName("sound")
    public val sound: NotificationSound? = null,
    @SerialName("stories_muted")
    @TLConditional("flags", 6)
    @get:JvmName("storiesMuted")
    public val storiesMuted: Boolean? = null,
    @SerialName("stories_hide_sender")
    @TLConditional("flags", 7)
    @get:JvmName("storiesHideSender")
    public val storiesHideSender: Boolean? = null,
    @SerialName("stories_sound")
    @TLConditional("flags", 8)
    @get:JvmName("storiesSound")
    public val storiesSound: NotificationSound? = null,
) {
    public companion object
}
