// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface InputUser {
    @Serializable
    @SerialName("inputUserEmpty")
    @TLCombinatorId(0xB98886CF)
    public object InputUserEmpty : tl.telegram.InputUser

    @Serializable
    @SerialName("inputUserSelf")
    @TLCombinatorId(0xF7C1B13F)
    public object InputUserSelf : tl.telegram.InputUser

    @Serializable
    @SerialName("inputUser")
    @TLCombinatorId(0xF21158C6)
    public data class InputUser(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @SerialName("access_hash")
        @get:JvmName("accessHash")
        public val accessHash: Long,
    ) : tl.telegram.InputUser {
        public companion object
    }

    @Serializable
    @SerialName("inputUserFromMessage")
    @TLCombinatorId(0x1DA448E2)
    public data class InputUserFromMessage(
        @get:JvmName("peer")
        public val peer: InputPeer,
        @SerialName("msg_id")
        @get:JvmName("msgId")
        public val msgId: Int,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
    ) : tl.telegram.InputUser {
        public companion object
    }

    public companion object
}
