// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface JSONValue {
    @Serializable
    @SerialName("jsonNull")
    @TLCombinatorId(0x3F6D7B68)
    public object JsonNull : JSONValue

    @Serializable
    @SerialName("jsonBool")
    @TLCombinatorId(0xC7345E6A)
    public data class JsonBool(
        @get:JvmName("value")
        public val `value`: Boolean,
    ) : JSONValue {
        public companion object
    }

    @Serializable
    @SerialName("jsonNumber")
    @TLCombinatorId(0x2BE0DFA4)
    public data class JsonNumber(
        @get:JvmName("value")
        public val `value`: Double,
    ) : JSONValue {
        public companion object
    }

    @Serializable
    @SerialName("jsonString")
    @TLCombinatorId(0xB71E767A)
    public data class JsonString(
        @get:JvmName("value")
        public val `value`: String,
    ) : JSONValue {
        public companion object
    }

    @Serializable
    @SerialName("jsonArray")
    @TLCombinatorId(0xF7444763)
    public data class JsonArray(
        @get:JvmName("value")
        public val `value`: List<JSONValue>,
    ) : JSONValue {
        public companion object
    }

    @Serializable
    @SerialName("jsonObject")
    @TLCombinatorId(0x99C1D49D)
    public data class JsonObject(
        @get:JvmName("value")
        public val `value`: List<JSONObjectValue>,
    ) : JSONValue {
        public companion object
    }

    public companion object
}
