// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("jsonObjectValue")
@TLCombinatorId(0xC0DE1BD9)
public data class JSONObjectValue(
    @get:JvmName("key")
    public val key: String,
    @get:JvmName("value")
    public val `value`: JSONValue,
) {
    public companion object
}
