// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface MessagesFilter {
    @Serializable
    @SerialName("inputMessagesFilterEmpty")
    @TLCombinatorId(0x57E2F66C)
    public object InputMessagesFilterEmpty : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterPhotos")
    @TLCombinatorId(0x9609A51C)
    public object InputMessagesFilterPhotos : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterVideo")
    @TLCombinatorId(0x9FC00E65)
    public object InputMessagesFilterVideo : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterPhotoVideo")
    @TLCombinatorId(0x56E9F0E4)
    public object InputMessagesFilterPhotoVideo : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterDocument")
    @TLCombinatorId(0x9EDDF188)
    public object InputMessagesFilterDocument : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterUrl")
    @TLCombinatorId(0x7EF0DD87)
    public object InputMessagesFilterUrl : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterGif")
    @TLCombinatorId(0xFFC86587)
    public object InputMessagesFilterGif : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterVoice")
    @TLCombinatorId(0x50F5C392)
    public object InputMessagesFilterVoice : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterMusic")
    @TLCombinatorId(0x3751B49E)
    public object InputMessagesFilterMusic : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterChatPhotos")
    @TLCombinatorId(0x3A20ECB8)
    public object InputMessagesFilterChatPhotos : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterPhoneCalls")
    @TLCombinatorId(0x80C99768)
    public data class InputMessagesFilterPhoneCalls(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("missed")
        public val missed: Unit? = null,
    ) : MessagesFilter {
        public companion object
    }

    @Serializable
    @SerialName("inputMessagesFilterRoundVoice")
    @TLCombinatorId(0x7A7C17A4)
    public object InputMessagesFilterRoundVoice : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterRoundVideo")
    @TLCombinatorId(0xB549DA53)
    public object InputMessagesFilterRoundVideo : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterMyMentions")
    @TLCombinatorId(0xC1F8E69A)
    public object InputMessagesFilterMyMentions : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterGeo")
    @TLCombinatorId(0xE7026D0D)
    public object InputMessagesFilterGeo : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterContacts")
    @TLCombinatorId(0xE062DB83)
    public object InputMessagesFilterContacts : MessagesFilter

    @Serializable
    @SerialName("inputMessagesFilterPinned")
    @TLCombinatorId(0x1BB00451)
    public object InputMessagesFilterPinned : MessagesFilter

    public companion object
}
