// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface MessageEntity {
    @Serializable
    @SerialName("messageEntityUnknown")
    @TLCombinatorId(0xBB92BA95)
    public data class MessageEntityUnknown(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityMention")
    @TLCombinatorId(0xFA04579D)
    public data class MessageEntityMention(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityHashtag")
    @TLCombinatorId(0x6F635B0D)
    public data class MessageEntityHashtag(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityBotCommand")
    @TLCombinatorId(0x6CEF8AC7)
    public data class MessageEntityBotCommand(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityUrl")
    @TLCombinatorId(0x6ED02538)
    public data class MessageEntityUrl(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityEmail")
    @TLCombinatorId(0x64E475C2)
    public data class MessageEntityEmail(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityBold")
    @TLCombinatorId(0xBD610BC9)
    public data class MessageEntityBold(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityItalic")
    @TLCombinatorId(0x826F8B60)
    public data class MessageEntityItalic(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityCode")
    @TLCombinatorId(0x28A20571)
    public data class MessageEntityCode(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityPre")
    @TLCombinatorId(0x73924BE0)
    public data class MessageEntityPre(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
        @get:JvmName("language")
        public val language: String,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityTextUrl")
    @TLCombinatorId(0x76A6D327)
    public data class MessageEntityTextUrl(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
        @get:JvmName("url")
        public val url: String,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityMentionName")
    @TLCombinatorId(0xDC7B1140)
    public data class MessageEntityMentionName(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("inputMessageEntityMentionName")
    @TLCombinatorId(0x208E68C9)
    public data class InputMessageEntityMentionName(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: InputUser,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityPhone")
    @TLCombinatorId(0x9B69E34B)
    public data class MessageEntityPhone(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityCashtag")
    @TLCombinatorId(0x4C4E743F)
    public data class MessageEntityCashtag(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityUnderline")
    @TLCombinatorId(0x9C4E7E8B)
    public data class MessageEntityUnderline(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityStrike")
    @TLCombinatorId(0xBF0693D4)
    public data class MessageEntityStrike(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityBankCard")
    @TLCombinatorId(0x761E6AF4)
    public data class MessageEntityBankCard(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntitySpoiler")
    @TLCombinatorId(0x32CA960F)
    public data class MessageEntitySpoiler(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityCustomEmoji")
    @TLCombinatorId(0xC8CF05F8)
    public data class MessageEntityCustomEmoji(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
        @SerialName("document_id")
        @get:JvmName("documentId")
        public val documentId: Long,
    ) : MessageEntity {
        public companion object
    }

    @Serializable
    @SerialName("messageEntityBlockquote")
    @TLCombinatorId(0x20DF5D0)
    public data class MessageEntityBlockquote(
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("length")
        public val length: Int,
    ) : MessageEntity {
        public companion object
    }

    public companion object
}
