// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("messageFwdHeader")
@TLCombinatorId(0x5F777DCE)
public data class MessageFwdHeader(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 7)
    @get:JvmName("imported")
    public val imported: Unit? = null,
    @SerialName("from_id")
    @TLConditional("flags", 0)
    @get:JvmName("fromId")
    public val fromId: Peer? = null,
    @SerialName("from_name")
    @TLConditional("flags", 5)
    @get:JvmName("fromName")
    public val fromName: String? = null,
    @get:JvmName("date")
    public val date: Int,
    @SerialName("channel_post")
    @TLConditional("flags", 2)
    @get:JvmName("channelPost")
    public val channelPost: Int? = null,
    @SerialName("post_author")
    @TLConditional("flags", 3)
    @get:JvmName("postAuthor")
    public val postAuthor: String? = null,
    @SerialName("saved_from_peer")
    @TLConditional("flags", 4)
    @get:JvmName("savedFromPeer")
    public val savedFromPeer: Peer? = null,
    @SerialName("saved_from_msg_id")
    @TLConditional("flags", 4)
    @get:JvmName("savedFromMsgId")
    public val savedFromMsgId: Int? = null,
    @SerialName("psa_type")
    @TLConditional("flags", 6)
    @get:JvmName("psaType")
    public val psaType: String? = null,
) {
    public companion object
}
