// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface MessageExtendedMedia {
    @Serializable
    @SerialName("messageExtendedMediaPreview")
    @TLCombinatorId(0xAD628CC8)
    public data class MessageExtendedMediaPreview(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("w")
        public val w: Int? = null,
        @TLConditional("flags", 0)
        @get:JvmName("h")
        public val h: Int? = null,
        @TLConditional("flags", 1)
        @get:JvmName("thumb")
        public val thumb: PhotoSize? = null,
        @SerialName("video_duration")
        @TLConditional("flags", 2)
        @get:JvmName("videoDuration")
        public val videoDuration: Int? = null,
    ) : tl.telegram.MessageExtendedMedia {
        public companion object
    }

    @Serializable
    @SerialName("messageExtendedMedia")
    @TLCombinatorId(0xEE479C64)
    public data class MessageExtendedMedia(
        @get:JvmName("media")
        public val media: MessageMedia,
    ) : tl.telegram.MessageExtendedMedia {
        public companion object
    }

    public companion object
}
