// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface NotificationSound {
    @Serializable
    @SerialName("notificationSoundDefault")
    @TLCombinatorId(0x97E8BEBE)
    public object NotificationSoundDefault : NotificationSound

    @Serializable
    @SerialName("notificationSoundNone")
    @TLCombinatorId(0x6F0C34DF)
    public object NotificationSoundNone : NotificationSound

    @Serializable
    @SerialName("notificationSoundLocal")
    @TLCombinatorId(0x830B9AE4)
    public data class NotificationSoundLocal(
        @get:JvmName("title")
        public val title: String,
        @get:JvmName("data")
        public val `data`: String,
    ) : NotificationSound {
        public companion object
    }

    @Serializable
    @SerialName("notificationSoundRingtone")
    @TLCombinatorId(0xFF6C8049)
    public data class NotificationSoundRingtone(
        @get:JvmName("id")
        public val id: Long,
    ) : NotificationSound {
        public companion object
    }

    public companion object
}
