// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("pageTableCell")
@TLCombinatorId(0x34566B6A)
public data class PageTableCell(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("header")
    public val `header`: Unit? = null,
    @SerialName("align_center")
    @TLConditional("flags", 3)
    @get:JvmName("alignCenter")
    public val alignCenter: Unit? = null,
    @SerialName("align_right")
    @TLConditional("flags", 4)
    @get:JvmName("alignRight")
    public val alignRight: Unit? = null,
    @SerialName("valign_middle")
    @TLConditional("flags", 5)
    @get:JvmName("valignMiddle")
    public val valignMiddle: Unit? = null,
    @SerialName("valign_bottom")
    @TLConditional("flags", 6)
    @get:JvmName("valignBottom")
    public val valignBottom: Unit? = null,
    @TLConditional("flags", 7)
    @get:JvmName("text")
    public val text: RichText? = null,
    @TLConditional("flags", 1)
    @get:JvmName("colspan")
    public val colspan: Int? = null,
    @TLConditional("flags", 2)
    @get:JvmName("rowspan")
    public val rowspan: Int? = null,
) {
    public companion object
}
