// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("peerNotifySettings")
@TLCombinatorId(0x99622C0C)
public data class PeerNotifySettings(
    @get:JvmName("flags")
    public val flags: Int,
    @SerialName("show_previews")
    @TLConditional("flags", 0)
    @get:JvmName("showPreviews")
    public val showPreviews: Boolean? = null,
    @TLConditional("flags", 1)
    @get:JvmName("silent")
    public val silent: Boolean? = null,
    @SerialName("mute_until")
    @TLConditional("flags", 2)
    @get:JvmName("muteUntil")
    public val muteUntil: Int? = null,
    @SerialName("ios_sound")
    @TLConditional("flags", 3)
    @get:JvmName("iosSound")
    public val iosSound: NotificationSound? = null,
    @SerialName("android_sound")
    @TLConditional("flags", 4)
    @get:JvmName("androidSound")
    public val androidSound: NotificationSound? = null,
    @SerialName("other_sound")
    @TLConditional("flags", 5)
    @get:JvmName("otherSound")
    public val otherSound: NotificationSound? = null,
    @SerialName("stories_muted")
    @TLConditional("flags", 6)
    @get:JvmName("storiesMuted")
    public val storiesMuted: Boolean? = null,
    @SerialName("stories_hide_sender")
    @TLConditional("flags", 7)
    @get:JvmName("storiesHideSender")
    public val storiesHideSender: Boolean? = null,
    @SerialName("stories_ios_sound")
    @TLConditional("flags", 8)
    @get:JvmName("storiesIosSound")
    public val storiesIosSound: NotificationSound? = null,
    @SerialName("stories_android_sound")
    @TLConditional("flags", 9)
    @get:JvmName("storiesAndroidSound")
    public val storiesAndroidSound: NotificationSound? = null,
    @SerialName("stories_other_sound")
    @TLConditional("flags", 10)
    @get:JvmName("storiesOtherSound")
    public val storiesOtherSound: NotificationSound? = null,
) {
    public companion object
}
