// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("phoneCallProtocol")
@TLCombinatorId(0xFC878FC8)
public data class PhoneCallProtocol(
    @get:JvmName("flags")
    public val flags: Int,
    @SerialName("udp_p2p")
    @TLConditional("flags", 0)
    @get:JvmName("udpP2p")
    public val udpP2p: Unit? = null,
    @SerialName("udp_reflector")
    @TLConditional("flags", 1)
    @get:JvmName("udpReflector")
    public val udpReflector: Unit? = null,
    @SerialName("min_layer")
    @get:JvmName("minLayer")
    public val minLayer: Int,
    @SerialName("max_layer")
    @get:JvmName("maxLayer")
    public val maxLayer: Int,
    @SerialName("library_versions")
    @get:JvmName("libraryVersions")
    public val libraryVersions: List<String>,
) {
    public companion object
}
