// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("premiumSubscriptionOption")
@TLCombinatorId(0x5F2D1DF2)
public data class PremiumSubscriptionOption(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 1)
    @get:JvmName("current")
    public val current: Unit? = null,
    @SerialName("can_purchase_upgrade")
    @TLConditional("flags", 2)
    @get:JvmName("canPurchaseUpgrade")
    public val canPurchaseUpgrade: Unit? = null,
    @TLConditional("flags", 3)
    @get:JvmName("transaction")
    public val transaction: String? = null,
    @get:JvmName("months")
    public val months: Int,
    @get:JvmName("currency")
    public val currency: String,
    @get:JvmName("amount")
    public val amount: Long,
    @SerialName("bot_url")
    @get:JvmName("botUrl")
    public val botUrl: String,
    @SerialName("store_product")
    @TLConditional("flags", 0)
    @get:JvmName("storeProduct")
    public val storeProduct: String? = null,
) {
    public companion object
}
