// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class ReportReason {
    @SerialName("inputReportReasonSpam")
    @TLCombinatorId(0x58DBCAB8)
    INPUT_REPORT_REASON_SPAM,
    @SerialName("inputReportReasonViolence")
    @TLCombinatorId(0x1E22C78D)
    INPUT_REPORT_REASON_VIOLENCE,
    @SerialName("inputReportReasonPornography")
    @TLCombinatorId(0x2E59D922)
    INPUT_REPORT_REASON_PORNOGRAPHY,
    @SerialName("inputReportReasonChildAbuse")
    @TLCombinatorId(0xADF44EE3)
    INPUT_REPORT_REASON_CHILD_ABUSE,
    @SerialName("inputReportReasonOther")
    @TLCombinatorId(0xC1E4A2B1)
    INPUT_REPORT_REASON_OTHER,
    @SerialName("inputReportReasonCopyright")
    @TLCombinatorId(0x9B89F93A)
    INPUT_REPORT_REASON_COPYRIGHT,
    @SerialName("inputReportReasonGeoIrrelevant")
    @TLCombinatorId(0xDBD4FEED)
    INPUT_REPORT_REASON_GEO_IRRELEVANT,
    @SerialName("inputReportReasonFake")
    @TLCombinatorId(0xF5DDD6E7)
    INPUT_REPORT_REASON_FAKE,
    @SerialName("inputReportReasonIllegalDrugs")
    @TLCombinatorId(0xA8EB2BE)
    INPUT_REPORT_REASON_ILLEGAL_DRUGS,
    @SerialName("inputReportReasonPersonalDetails")
    @TLCombinatorId(0x9EC7863D)
    INPUT_REPORT_REASON_PERSONAL_DETAILS,
    ;

    public companion object
}
