// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("stickerSet")
@TLCombinatorId(0x2DD14EDC)
public data class StickerSet(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 1)
    @get:JvmName("archived")
    public val archived: Unit? = null,
    @TLConditional("flags", 2)
    @get:JvmName("official")
    public val official: Unit? = null,
    @TLConditional("flags", 3)
    @get:JvmName("masks")
    public val masks: Unit? = null,
    @TLConditional("flags", 5)
    @get:JvmName("animated")
    public val animated: Unit? = null,
    @TLConditional("flags", 6)
    @get:JvmName("videos")
    public val videos: Unit? = null,
    @TLConditional("flags", 7)
    @get:JvmName("emojis")
    public val emojis: Unit? = null,
    @SerialName("text_color")
    @TLConditional("flags", 9)
    @get:JvmName("textColor")
    public val textColor: Unit? = null,
    @SerialName("installed_date")
    @TLConditional("flags", 0)
    @get:JvmName("installedDate")
    public val installedDate: Int? = null,
    @get:JvmName("id")
    public val id: Long,
    @SerialName("access_hash")
    @get:JvmName("accessHash")
    public val accessHash: Long,
    @get:JvmName("title")
    public val title: String,
    @SerialName("short_name")
    @get:JvmName("shortName")
    public val shortName: String,
    @TLConditional("flags", 4)
    @get:JvmName("thumbs")
    public val thumbs: List<PhotoSize>? = null,
    @SerialName("thumb_dc_id")
    @TLConditional("flags", 4)
    @get:JvmName("thumbDcId")
    public val thumbDcId: Int? = null,
    @SerialName("thumb_version")
    @TLConditional("flags", 4)
    @get:JvmName("thumbVersion")
    public val thumbVersion: Int? = null,
    @SerialName("thumb_document_id")
    @TLConditional("flags", 8)
    @get:JvmName("thumbDocumentId")
    public val thumbDocumentId: Long? = null,
    @get:JvmName("count")
    public val count: Int,
    @get:JvmName("hash")
    public val hash: Int,
) {
    public companion object
}
