// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("theme")
@TLCombinatorId(0xA00E67D6)
public data class Theme(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("creator")
    public val creator: Unit? = null,
    @TLConditional("flags", 1)
    @get:JvmName("default")
    public val default: Unit? = null,
    @SerialName("for_chat")
    @TLConditional("flags", 5)
    @get:JvmName("forChat")
    public val forChat: Unit? = null,
    @get:JvmName("id")
    public val id: Long,
    @SerialName("access_hash")
    @get:JvmName("accessHash")
    public val accessHash: Long,
    @get:JvmName("slug")
    public val slug: String,
    @get:JvmName("title")
    public val title: String,
    @TLConditional("flags", 2)
    @get:JvmName("document")
    public val document: Document? = null,
    @TLConditional("flags", 3)
    @get:JvmName("settings")
    public val settings: List<ThemeSettings>? = null,
    @TLConditional("flags", 6)
    @get:JvmName("emoticon")
    public val emoticon: String? = null,
    @SerialName("installs_count")
    @TLConditional("flags", 4)
    @get:JvmName("installsCount")
    public val installsCount: Int? = null,
) {
    public companion object
}
