// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import tl.telegram.messages.MessagesStickerSet

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface Update {
    @Serializable
    @SerialName("updateNewMessage")
    @TLCombinatorId(0x1F2B0AFD)
    public data class UpdateNewMessage(
        @get:JvmName("message")
        public val message: Message,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateMessageID")
    @TLCombinatorId(0x4E90BFD6)
    public data class UpdateMessageID(
        @get:JvmName("id")
        public val id: Int,
        @SerialName("random_id")
        @get:JvmName("randomId")
        public val randomId: Long,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateDeleteMessages")
    @TLCombinatorId(0xA20DB0E5)
    public data class UpdateDeleteMessages(
        @get:JvmName("messages")
        public val messages: List<Int>,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateUserTyping")
    @TLCombinatorId(0xC01E857F)
    public data class UpdateUserTyping(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("action")
        public val action: SendMessageAction,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChatUserTyping")
    @TLCombinatorId(0x83487AF0)
    public data class UpdateChatUserTyping(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Long,
        @SerialName("from_id")
        @get:JvmName("fromId")
        public val fromId: Peer,
        @get:JvmName("action")
        public val action: SendMessageAction,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChatParticipants")
    @TLCombinatorId(0x7761198)
    public data class UpdateChatParticipants(
        @get:JvmName("participants")
        public val participants: ChatParticipants,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateUserStatus")
    @TLCombinatorId(0xE5BDF8DE)
    public data class UpdateUserStatus(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("status")
        public val status: UserStatus,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateUserName")
    @TLCombinatorId(0xA7848924)
    public data class UpdateUserName(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @SerialName("first_name")
        @get:JvmName("firstName")
        public val firstName: String,
        @SerialName("last_name")
        @get:JvmName("lastName")
        public val lastName: String,
        @get:JvmName("usernames")
        public val usernames: List<Username>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateNewAuthorization")
    @TLCombinatorId(0x8951ABEF)
    public data class UpdateNewAuthorization(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("unconfirmed")
        public val unconfirmed: Unit? = null,
        @get:JvmName("hash")
        public val hash: Long,
        @TLConditional("flags", 0)
        @get:JvmName("date")
        public val date: Int? = null,
        @TLConditional("flags", 0)
        @get:JvmName("device")
        public val device: String? = null,
        @TLConditional("flags", 0)
        @get:JvmName("location")
        public val location: String? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateNewEncryptedMessage")
    @TLCombinatorId(0x12BCBD9A)
    public data class UpdateNewEncryptedMessage(
        @get:JvmName("message")
        public val message: EncryptedMessage,
        @get:JvmName("qts")
        public val qts: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateEncryptedChatTyping")
    @TLCombinatorId(0x1710F156)
    public data class UpdateEncryptedChatTyping(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateEncryption")
    @TLCombinatorId(0xB4A2E88D)
    public data class UpdateEncryption(
        @get:JvmName("chat")
        public val chat: EncryptedChat,
        @get:JvmName("date")
        public val date: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateEncryptedMessagesRead")
    @TLCombinatorId(0x38FE25B7)
    public data class UpdateEncryptedMessagesRead(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Int,
        @SerialName("max_date")
        @get:JvmName("maxDate")
        public val maxDate: Int,
        @get:JvmName("date")
        public val date: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChatParticipantAdd")
    @TLCombinatorId(0x3DDA5451)
    public data class UpdateChatParticipantAdd(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Long,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @SerialName("inviter_id")
        @get:JvmName("inviterId")
        public val inviterId: Long,
        @get:JvmName("date")
        public val date: Int,
        @get:JvmName("version")
        public val version: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChatParticipantDelete")
    @TLCombinatorId(0xE32F3D77)
    public data class UpdateChatParticipantDelete(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Long,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("version")
        public val version: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateDcOptions")
    @TLCombinatorId(0x8E5E9873)
    public data class UpdateDcOptions(
        @SerialName("dc_options")
        @get:JvmName("dcOptions")
        public val dcOptions: List<DcOption>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateNotifySettings")
    @TLCombinatorId(0xBEC268EF)
    public data class UpdateNotifySettings(
        @get:JvmName("peer")
        public val peer: NotifyPeer,
        @SerialName("notify_settings")
        @get:JvmName("notifySettings")
        public val notifySettings: PeerNotifySettings,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateServiceNotification")
    @TLCombinatorId(0xEBE46819)
    public data class UpdateServiceNotification(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("popup")
        public val popup: Unit? = null,
        @SerialName("invert_media")
        @TLConditional("flags", 2)
        @get:JvmName("invertMedia")
        public val invertMedia: Unit? = null,
        @SerialName("inbox_date")
        @TLConditional("flags", 1)
        @get:JvmName("inboxDate")
        public val inboxDate: Int? = null,
        @get:JvmName("type")
        public val type: String,
        @get:JvmName("message")
        public val message: String,
        @get:JvmName("media")
        public val media: MessageMedia,
        @get:JvmName("entities")
        public val entities: List<MessageEntity>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updatePrivacy")
    @TLCombinatorId(0xEE3B272A)
    public data class UpdatePrivacy(
        @get:JvmName("key")
        public val key: PrivacyKey,
        @get:JvmName("rules")
        public val rules: List<PrivacyRule>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateUserPhone")
    @TLCombinatorId(0x5492A13)
    public data class UpdateUserPhone(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("phone")
        public val phone: String,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateReadHistoryInbox")
    @TLCombinatorId(0x9C974FDF)
    public data class UpdateReadHistoryInbox(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("folder_id")
        @TLConditional("flags", 0)
        @get:JvmName("folderId")
        public val folderId: Int? = null,
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("max_id")
        @get:JvmName("maxId")
        public val maxId: Int,
        @SerialName("still_unread_count")
        @get:JvmName("stillUnreadCount")
        public val stillUnreadCount: Int,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateReadHistoryOutbox")
    @TLCombinatorId(0x2F2F21BF)
    public data class UpdateReadHistoryOutbox(
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("max_id")
        @get:JvmName("maxId")
        public val maxId: Int,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateWebPage")
    @TLCombinatorId(0x7F891213)
    public data class UpdateWebPage(
        @get:JvmName("webpage")
        public val webpage: WebPage,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateReadMessagesContents")
    @TLCombinatorId(0xF8227181)
    public data class UpdateReadMessagesContents(
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("messages")
        public val messages: List<Int>,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
        @TLConditional("flags", 0)
        @get:JvmName("date")
        public val date: Int? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChannelTooLong")
    @TLCombinatorId(0x108D941F)
    public data class UpdateChannelTooLong(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @TLConditional("flags", 0)
        @get:JvmName("pts")
        public val pts: Int? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChannel")
    @TLCombinatorId(0x635B4C09)
    public data class UpdateChannel(
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateNewChannelMessage")
    @TLCombinatorId(0x62BA04D9)
    public data class UpdateNewChannelMessage(
        @get:JvmName("message")
        public val message: Message,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateReadChannelInbox")
    @TLCombinatorId(0x922E6E10)
    public data class UpdateReadChannelInbox(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("folder_id")
        @TLConditional("flags", 0)
        @get:JvmName("folderId")
        public val folderId: Int? = null,
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @SerialName("max_id")
        @get:JvmName("maxId")
        public val maxId: Int,
        @SerialName("still_unread_count")
        @get:JvmName("stillUnreadCount")
        public val stillUnreadCount: Int,
        @get:JvmName("pts")
        public val pts: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateDeleteChannelMessages")
    @TLCombinatorId(0xC32D5B12)
    public data class UpdateDeleteChannelMessages(
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @get:JvmName("messages")
        public val messages: List<Int>,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChannelMessageViews")
    @TLCombinatorId(0xF226AC08)
    public data class UpdateChannelMessageViews(
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @get:JvmName("id")
        public val id: Int,
        @get:JvmName("views")
        public val views: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChatParticipantAdmin")
    @TLCombinatorId(0xD7CA61A2)
    public data class UpdateChatParticipantAdmin(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Long,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @SerialName("is_admin")
        @get:JvmName("isAdmin")
        public val isAdmin: Boolean,
        @get:JvmName("version")
        public val version: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateNewStickerSet")
    @TLCombinatorId(0x688A30AA)
    public data class UpdateNewStickerSet(
        @get:JvmName("stickerset")
        public val stickerset: MessagesStickerSet,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateStickerSetsOrder")
    @TLCombinatorId(0xBB2D201)
    public data class UpdateStickerSetsOrder(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("masks")
        public val masks: Unit? = null,
        @TLConditional("flags", 1)
        @get:JvmName("emojis")
        public val emojis: Unit? = null,
        @get:JvmName("order")
        public val order: List<Long>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateStickerSets")
    @TLCombinatorId(0x31C24808)
    public data class UpdateStickerSets(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("masks")
        public val masks: Unit? = null,
        @TLConditional("flags", 1)
        @get:JvmName("emojis")
        public val emojis: Unit? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateSavedGifs")
    @TLCombinatorId(0x9375341E)
    public object UpdateSavedGifs : Update

    @Serializable
    @SerialName("updateBotInlineQuery")
    @TLCombinatorId(0x496F379C)
    public data class UpdateBotInlineQuery(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("query_id")
        @get:JvmName("queryId")
        public val queryId: Long,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("query")
        public val query: String,
        @TLConditional("flags", 0)
        @get:JvmName("geo")
        public val geo: GeoPoint? = null,
        @SerialName("peer_type")
        @TLConditional("flags", 1)
        @get:JvmName("peerType")
        public val peerType: InlineQueryPeerType? = null,
        @get:JvmName("offset")
        public val offset: String,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotInlineSend")
    @TLCombinatorId(0x12F12A07)
    public data class UpdateBotInlineSend(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("query")
        public val query: String,
        @TLConditional("flags", 0)
        @get:JvmName("geo")
        public val geo: GeoPoint? = null,
        @get:JvmName("id")
        public val id: String,
        @SerialName("msg_id")
        @TLConditional("flags", 1)
        @get:JvmName("msgId")
        public val msgId: InputBotInlineMessageID? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateEditChannelMessage")
    @TLCombinatorId(0x1B3F4DF7)
    public data class UpdateEditChannelMessage(
        @get:JvmName("message")
        public val message: Message,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotCallbackQuery")
    @TLCombinatorId(0xB9CFC48D)
    public data class UpdateBotCallbackQuery(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("query_id")
        @get:JvmName("queryId")
        public val queryId: Long,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("msg_id")
        @get:JvmName("msgId")
        public val msgId: Int,
        @SerialName("chat_instance")
        @get:JvmName("chatInstance")
        public val chatInstance: Long,
        @TLConditional("flags", 0)
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString? = null,
        @SerialName("game_short_name")
        @TLConditional("flags", 1)
        @get:JvmName("gameShortName")
        public val gameShortName: String? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateEditMessage")
    @TLCombinatorId(0xE40370A3)
    public data class UpdateEditMessage(
        @get:JvmName("message")
        public val message: Message,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateInlineBotCallbackQuery")
    @TLCombinatorId(0x691E9052)
    public data class UpdateInlineBotCallbackQuery(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("query_id")
        @get:JvmName("queryId")
        public val queryId: Long,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @SerialName("msg_id")
        @get:JvmName("msgId")
        public val msgId: InputBotInlineMessageID,
        @SerialName("chat_instance")
        @get:JvmName("chatInstance")
        public val chatInstance: Long,
        @TLConditional("flags", 0)
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString? = null,
        @SerialName("game_short_name")
        @TLConditional("flags", 1)
        @get:JvmName("gameShortName")
        public val gameShortName: String? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateReadChannelOutbox")
    @TLCombinatorId(0xB75F99A9)
    public data class UpdateReadChannelOutbox(
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @SerialName("max_id")
        @get:JvmName("maxId")
        public val maxId: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateDraftMessage")
    @TLCombinatorId(0x1B49EC6D)
    public data class UpdateDraftMessage(
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("top_msg_id")
        @TLConditional("flags", 0)
        @get:JvmName("topMsgId")
        public val topMsgId: Int? = null,
        @get:JvmName("draft")
        public val draft: DraftMessage,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateReadFeaturedStickers")
    @TLCombinatorId(0x571D2742)
    public object UpdateReadFeaturedStickers : Update

    @Serializable
    @SerialName("updateRecentStickers")
    @TLCombinatorId(0x9A422C20)
    public object UpdateRecentStickers : Update

    @Serializable
    @SerialName("updateConfig")
    @TLCombinatorId(0xA229DD06)
    public object UpdateConfig : Update

    @Serializable
    @SerialName("updatePtsChanged")
    @TLCombinatorId(0x3354678F)
    public object UpdatePtsChanged : Update

    @Serializable
    @SerialName("updateChannelWebPage")
    @TLCombinatorId(0x2F2BA99F)
    public data class UpdateChannelWebPage(
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @get:JvmName("webpage")
        public val webpage: WebPage,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateDialogPinned")
    @TLCombinatorId(0x6E6FE51C)
    public data class UpdateDialogPinned(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("pinned")
        public val pinned: Unit? = null,
        @SerialName("folder_id")
        @TLConditional("flags", 1)
        @get:JvmName("folderId")
        public val folderId: Int? = null,
        @get:JvmName("peer")
        public val peer: DialogPeer,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updatePinnedDialogs")
    @TLCombinatorId(0xFA0F3CA2)
    public data class UpdatePinnedDialogs(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("folder_id")
        @TLConditional("flags", 1)
        @get:JvmName("folderId")
        public val folderId: Int? = null,
        @TLConditional("flags", 0)
        @get:JvmName("order")
        public val order: List<DialogPeer>? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotWebhookJSON")
    @TLCombinatorId(0x8317C0C3)
    public data class UpdateBotWebhookJSON(
        @get:JvmName("data")
        public val `data`: DataJSON,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotWebhookJSONQuery")
    @TLCombinatorId(0x9B9240A6)
    public data class UpdateBotWebhookJSONQuery(
        @SerialName("query_id")
        @get:JvmName("queryId")
        public val queryId: Long,
        @get:JvmName("data")
        public val `data`: DataJSON,
        @get:JvmName("timeout")
        public val timeout: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotShippingQuery")
    @TLCombinatorId(0xB5AEFD7D)
    public data class UpdateBotShippingQuery(
        @SerialName("query_id")
        @get:JvmName("queryId")
        public val queryId: Long,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("payload")
        public val payload: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("shipping_address")
        @get:JvmName("shippingAddress")
        public val shippingAddress: PostAddress,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotPrecheckoutQuery")
    @TLCombinatorId(0x8CAA9A96)
    public data class UpdateBotPrecheckoutQuery(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("query_id")
        @get:JvmName("queryId")
        public val queryId: Long,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("payload")
        public val payload: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @TLConditional("flags", 0)
        @get:JvmName("info")
        public val info: PaymentRequestedInfo? = null,
        @SerialName("shipping_option_id")
        @TLConditional("flags", 1)
        @get:JvmName("shippingOptionId")
        public val shippingOptionId: String? = null,
        @get:JvmName("currency")
        public val currency: String,
        @SerialName("total_amount")
        @get:JvmName("totalAmount")
        public val totalAmount: Long,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updatePhoneCall")
    @TLCombinatorId(0xAB0F6B1E)
    public data class UpdatePhoneCall(
        @SerialName("phone_call")
        @get:JvmName("phoneCall")
        public val phoneCall: PhoneCall,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateLangPackTooLong")
    @TLCombinatorId(0x46560264)
    public data class UpdateLangPackTooLong(
        @SerialName("lang_code")
        @get:JvmName("langCode")
        public val langCode: String,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateLangPack")
    @TLCombinatorId(0x56022F4D)
    public data class UpdateLangPack(
        @get:JvmName("difference")
        public val difference: LangPackDifference,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateFavedStickers")
    @TLCombinatorId(0xE511996D)
    public object UpdateFavedStickers : Update

    @Serializable
    @SerialName("updateChannelReadMessagesContents")
    @TLCombinatorId(0xEA29055D)
    public data class UpdateChannelReadMessagesContents(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @SerialName("top_msg_id")
        @TLConditional("flags", 0)
        @get:JvmName("topMsgId")
        public val topMsgId: Int? = null,
        @get:JvmName("messages")
        public val messages: List<Int>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateContactsReset")
    @TLCombinatorId(0x7084A7BE)
    public object UpdateContactsReset : Update

    @Serializable
    @SerialName("updateChannelAvailableMessages")
    @TLCombinatorId(0xB23FC698)
    public data class UpdateChannelAvailableMessages(
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @SerialName("available_min_id")
        @get:JvmName("availableMinId")
        public val availableMinId: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateDialogUnreadMark")
    @TLCombinatorId(0xE16459C3)
    public data class UpdateDialogUnreadMark(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("unread")
        public val unread: Unit? = null,
        @get:JvmName("peer")
        public val peer: DialogPeer,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateMessagePoll")
    @TLCombinatorId(0xACA1657B)
    public data class UpdateMessagePoll(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("poll_id")
        @get:JvmName("pollId")
        public val pollId: Long,
        @TLConditional("flags", 0)
        @get:JvmName("poll")
        public val poll: Poll? = null,
        @get:JvmName("results")
        public val results: PollResults,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChatDefaultBannedRights")
    @TLCombinatorId(0x54C01850)
    public data class UpdateChatDefaultBannedRights(
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("default_banned_rights")
        @get:JvmName("defaultBannedRights")
        public val defaultBannedRights: ChatBannedRights,
        @get:JvmName("version")
        public val version: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateFolderPeers")
    @TLCombinatorId(0x19360DC0)
    public data class UpdateFolderPeers(
        @SerialName("folder_peers")
        @get:JvmName("folderPeers")
        public val folderPeers: List<FolderPeer>,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updatePeerSettings")
    @TLCombinatorId(0x6A7E7366)
    public data class UpdatePeerSettings(
        @get:JvmName("peer")
        public val peer: Peer,
        @get:JvmName("settings")
        public val settings: PeerSettings,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updatePeerLocated")
    @TLCombinatorId(0xB4AFCFB0)
    public data class UpdatePeerLocated(
        @get:JvmName("peers")
        public val peers: List<PeerLocated>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateNewScheduledMessage")
    @TLCombinatorId(0x39A51DFB)
    public data class UpdateNewScheduledMessage(
        @get:JvmName("message")
        public val message: Message,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateDeleteScheduledMessages")
    @TLCombinatorId(0x90866CEE)
    public data class UpdateDeleteScheduledMessages(
        @get:JvmName("peer")
        public val peer: Peer,
        @get:JvmName("messages")
        public val messages: List<Int>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateTheme")
    @TLCombinatorId(0x8216FBA3)
    public data class UpdateTheme(
        @get:JvmName("theme")
        public val theme: Theme,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateGeoLiveViewed")
    @TLCombinatorId(0x871FB939)
    public data class UpdateGeoLiveViewed(
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("msg_id")
        @get:JvmName("msgId")
        public val msgId: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateLoginToken")
    @TLCombinatorId(0x564FE691)
    public object UpdateLoginToken : Update

    @Serializable
    @SerialName("updateMessagePollVote")
    @TLCombinatorId(0x24F40E77)
    public data class UpdateMessagePollVote(
        @SerialName("poll_id")
        @get:JvmName("pollId")
        public val pollId: Long,
        @get:JvmName("peer")
        public val peer: Peer,
        @get:JvmName("options")
        public val options: List<@Serializable(Base64ByteStringSerializer::class) ByteString>,
        @get:JvmName("qts")
        public val qts: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateDialogFilter")
    @TLCombinatorId(0x26FFDE7D)
    public data class UpdateDialogFilter(
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("id")
        public val id: Int,
        @TLConditional("flags", 0)
        @get:JvmName("filter")
        public val filter: DialogFilter? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateDialogFilterOrder")
    @TLCombinatorId(0xA5D72105)
    public data class UpdateDialogFilterOrder(
        @get:JvmName("order")
        public val order: List<Int>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateDialogFilters")
    @TLCombinatorId(0x3504914F)
    public object UpdateDialogFilters : Update

    @Serializable
    @SerialName("updatePhoneCallSignalingData")
    @TLCombinatorId(0x2661BF09)
    public data class UpdatePhoneCallSignalingData(
        @SerialName("phone_call_id")
        @get:JvmName("phoneCallId")
        public val phoneCallId: Long,
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChannelMessageForwards")
    @TLCombinatorId(0xD29A27F4)
    public data class UpdateChannelMessageForwards(
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @get:JvmName("id")
        public val id: Int,
        @get:JvmName("forwards")
        public val forwards: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateReadChannelDiscussionInbox")
    @TLCombinatorId(0xD6B19546)
    public data class UpdateReadChannelDiscussionInbox(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @SerialName("top_msg_id")
        @get:JvmName("topMsgId")
        public val topMsgId: Int,
        @SerialName("read_max_id")
        @get:JvmName("readMaxId")
        public val readMaxId: Int,
        @SerialName("broadcast_id")
        @TLConditional("flags", 0)
        @get:JvmName("broadcastId")
        public val broadcastId: Long? = null,
        @SerialName("broadcast_post")
        @TLConditional("flags", 0)
        @get:JvmName("broadcastPost")
        public val broadcastPost: Int? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateReadChannelDiscussionOutbox")
    @TLCombinatorId(0x695C9E7C)
    public data class UpdateReadChannelDiscussionOutbox(
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @SerialName("top_msg_id")
        @get:JvmName("topMsgId")
        public val topMsgId: Int,
        @SerialName("read_max_id")
        @get:JvmName("readMaxId")
        public val readMaxId: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updatePeerBlocked")
    @TLCombinatorId(0xEBE07752)
    public data class UpdatePeerBlocked(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("blocked")
        public val blocked: Unit? = null,
        @SerialName("blocked_my_stories_from")
        @TLConditional("flags", 1)
        @get:JvmName("blockedMyStoriesFrom")
        public val blockedMyStoriesFrom: Unit? = null,
        @SerialName("peer_id")
        @get:JvmName("peerId")
        public val peerId: Peer,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChannelUserTyping")
    @TLCombinatorId(0x8C88C923)
    public data class UpdateChannelUserTyping(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @SerialName("top_msg_id")
        @TLConditional("flags", 0)
        @get:JvmName("topMsgId")
        public val topMsgId: Int? = null,
        @SerialName("from_id")
        @get:JvmName("fromId")
        public val fromId: Peer,
        @get:JvmName("action")
        public val action: SendMessageAction,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updatePinnedMessages")
    @TLCombinatorId(0xED85EAB5)
    public data class UpdatePinnedMessages(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("pinned")
        public val pinned: Unit? = null,
        @get:JvmName("peer")
        public val peer: Peer,
        @get:JvmName("messages")
        public val messages: List<Int>,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updatePinnedChannelMessages")
    @TLCombinatorId(0x5BB98608)
    public data class UpdatePinnedChannelMessages(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("pinned")
        public val pinned: Unit? = null,
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @get:JvmName("messages")
        public val messages: List<Int>,
        @get:JvmName("pts")
        public val pts: Int,
        @SerialName("pts_count")
        @get:JvmName("ptsCount")
        public val ptsCount: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChat")
    @TLCombinatorId(0xF89A6A4E)
    public data class UpdateChat(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Long,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateGroupCallParticipants")
    @TLCombinatorId(0xF2EBDB4E)
    public data class UpdateGroupCallParticipants(
        @get:JvmName("call")
        public val call: InputGroupCall,
        @get:JvmName("participants")
        public val participants: List<GroupCallParticipant>,
        @get:JvmName("version")
        public val version: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateGroupCall")
    @TLCombinatorId(0x14B24500)
    public data class UpdateGroupCall(
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Long,
        @get:JvmName("call")
        public val call: GroupCall,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updatePeerHistoryTTL")
    @TLCombinatorId(0xBB9BB9A5)
    public data class UpdatePeerHistoryTTL(
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("ttl_period")
        @TLConditional("flags", 0)
        @get:JvmName("ttlPeriod")
        public val ttlPeriod: Int? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChatParticipant")
    @TLCombinatorId(0xD087663A)
    public data class UpdateChatParticipant(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("chat_id")
        @get:JvmName("chatId")
        public val chatId: Long,
        @get:JvmName("date")
        public val date: Int,
        @SerialName("actor_id")
        @get:JvmName("actorId")
        public val actorId: Long,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @SerialName("prev_participant")
        @TLConditional("flags", 0)
        @get:JvmName("prevParticipant")
        public val prevParticipant: ChatParticipant? = null,
        @SerialName("new_participant")
        @TLConditional("flags", 1)
        @get:JvmName("newParticipant")
        public val newParticipant: ChatParticipant? = null,
        @TLConditional("flags", 2)
        @get:JvmName("invite")
        public val invite: ExportedChatInvite? = null,
        @get:JvmName("qts")
        public val qts: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChannelParticipant")
    @TLCombinatorId(0x985D3ABB)
    public data class UpdateChannelParticipant(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("via_chatlist")
        @TLConditional("flags", 3)
        @get:JvmName("viaChatlist")
        public val viaChatlist: Unit? = null,
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @get:JvmName("date")
        public val date: Int,
        @SerialName("actor_id")
        @get:JvmName("actorId")
        public val actorId: Long,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @SerialName("prev_participant")
        @TLConditional("flags", 0)
        @get:JvmName("prevParticipant")
        public val prevParticipant: ChannelParticipant? = null,
        @SerialName("new_participant")
        @TLConditional("flags", 1)
        @get:JvmName("newParticipant")
        public val newParticipant: ChannelParticipant? = null,
        @TLConditional("flags", 2)
        @get:JvmName("invite")
        public val invite: ExportedChatInvite? = null,
        @get:JvmName("qts")
        public val qts: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotStopped")
    @TLCombinatorId(0xC4870A49)
    public data class UpdateBotStopped(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("date")
        public val date: Int,
        @get:JvmName("stopped")
        public val stopped: Boolean,
        @get:JvmName("qts")
        public val qts: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateGroupCallConnection")
    @TLCombinatorId(0xB783982)
    public data class UpdateGroupCallConnection(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("presentation")
        public val presentation: Unit? = null,
        @get:JvmName("params")
        public val params: DataJSON,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotCommands")
    @TLCombinatorId(0x4D712F2E)
    public data class UpdateBotCommands(
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("bot_id")
        @get:JvmName("botId")
        public val botId: Long,
        @get:JvmName("commands")
        public val commands: List<BotCommand>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updatePendingJoinRequests")
    @TLCombinatorId(0x7063C3DB)
    public data class UpdatePendingJoinRequests(
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("requests_pending")
        @get:JvmName("requestsPending")
        public val requestsPending: Int,
        @SerialName("recent_requesters")
        @get:JvmName("recentRequesters")
        public val recentRequesters: List<Long>,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotChatInviteRequester")
    @TLCombinatorId(0x11DFA986)
    public data class UpdateBotChatInviteRequester(
        @get:JvmName("peer")
        public val peer: Peer,
        @get:JvmName("date")
        public val date: Int,
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @get:JvmName("about")
        public val about: String,
        @get:JvmName("invite")
        public val invite: ExportedChatInvite,
        @get:JvmName("qts")
        public val qts: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateMessageReactions")
    @TLCombinatorId(0x5E1B3CB8)
    public data class UpdateMessageReactions(
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("msg_id")
        @get:JvmName("msgId")
        public val msgId: Int,
        @SerialName("top_msg_id")
        @TLConditional("flags", 0)
        @get:JvmName("topMsgId")
        public val topMsgId: Int? = null,
        @get:JvmName("reactions")
        public val reactions: MessageReactions,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateAttachMenuBots")
    @TLCombinatorId(0x17B7A20B)
    public object UpdateAttachMenuBots : Update

    @Serializable
    @SerialName("updateWebViewResultSent")
    @TLCombinatorId(0x1592B79D)
    public data class UpdateWebViewResultSent(
        @SerialName("query_id")
        @get:JvmName("queryId")
        public val queryId: Long,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotMenuButton")
    @TLCombinatorId(0x14B85813)
    public data class UpdateBotMenuButton(
        @SerialName("bot_id")
        @get:JvmName("botId")
        public val botId: Long,
        @get:JvmName("button")
        public val button: BotMenuButton,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateSavedRingtones")
    @TLCombinatorId(0x74D8BE99)
    public object UpdateSavedRingtones : Update

    @Serializable
    @SerialName("updateTranscribedAudio")
    @TLCombinatorId(0x84CD5A)
    public data class UpdateTranscribedAudio(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("pending")
        public val pending: Unit? = null,
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("msg_id")
        @get:JvmName("msgId")
        public val msgId: Int,
        @SerialName("transcription_id")
        @get:JvmName("transcriptionId")
        public val transcriptionId: Long,
        @get:JvmName("text")
        public val text: String,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateReadFeaturedEmojiStickers")
    @TLCombinatorId(0xFB4C496C)
    public object UpdateReadFeaturedEmojiStickers : Update

    @Serializable
    @SerialName("updateUserEmojiStatus")
    @TLCombinatorId(0x28373599)
    public data class UpdateUserEmojiStatus(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
        @SerialName("emoji_status")
        @get:JvmName("emojiStatus")
        public val emojiStatus: EmojiStatus,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateRecentEmojiStatuses")
    @TLCombinatorId(0x30F443DB)
    public object UpdateRecentEmojiStatuses : Update

    @Serializable
    @SerialName("updateRecentReactions")
    @TLCombinatorId(0x6F7863F4)
    public object UpdateRecentReactions : Update

    @Serializable
    @SerialName("updateMoveStickerSetToTop")
    @TLCombinatorId(0x86FCCF85)
    public data class UpdateMoveStickerSetToTop(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("masks")
        public val masks: Unit? = null,
        @TLConditional("flags", 1)
        @get:JvmName("emojis")
        public val emojis: Unit? = null,
        @get:JvmName("stickerset")
        public val stickerset: Long,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateMessageExtendedMedia")
    @TLCombinatorId(0x5A73A98C)
    public data class UpdateMessageExtendedMedia(
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("msg_id")
        @get:JvmName("msgId")
        public val msgId: Int,
        @SerialName("extended_media")
        @get:JvmName("extendedMedia")
        public val extendedMedia: MessageExtendedMedia,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChannelPinnedTopic")
    @TLCombinatorId(0x192EFBE3)
    public data class UpdateChannelPinnedTopic(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("pinned")
        public val pinned: Unit? = null,
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @SerialName("topic_id")
        @get:JvmName("topicId")
        public val topicId: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateChannelPinnedTopics")
    @TLCombinatorId(0xFE198602)
    public data class UpdateChannelPinnedTopics(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("channel_id")
        @get:JvmName("channelId")
        public val channelId: Long,
        @TLConditional("flags", 0)
        @get:JvmName("order")
        public val order: List<Int>? = null,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateUser")
    @TLCombinatorId(0x20529438)
    public data class UpdateUser(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateAutoSaveSettings")
    @TLCombinatorId(0xEC05B097)
    public object UpdateAutoSaveSettings : Update

    @Serializable
    @SerialName("updateGroupInvitePrivacyForbidden")
    @TLCombinatorId(0xCCF08AD6)
    public data class UpdateGroupInvitePrivacyForbidden(
        @SerialName("user_id")
        @get:JvmName("userId")
        public val userId: Long,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateStory")
    @TLCombinatorId(0x75B3B798)
    public data class UpdateStory(
        @get:JvmName("peer")
        public val peer: Peer,
        @get:JvmName("story")
        public val story: StoryItem,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateReadStories")
    @TLCombinatorId(0xF74E932B)
    public data class UpdateReadStories(
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("max_id")
        @get:JvmName("maxId")
        public val maxId: Int,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateStoryID")
    @TLCombinatorId(0x1BF335B9)
    public data class UpdateStoryID(
        @get:JvmName("id")
        public val id: Int,
        @SerialName("random_id")
        @get:JvmName("randomId")
        public val randomId: Long,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateStoriesStealthMode")
    @TLCombinatorId(0x2C084DC1)
    public data class UpdateStoriesStealthMode(
        @SerialName("stealth_mode")
        @get:JvmName("stealthMode")
        public val stealthMode: StoriesStealthMode,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateSentStoryReaction")
    @TLCombinatorId(0x7D627683)
    public data class UpdateSentStoryReaction(
        @get:JvmName("peer")
        public val peer: Peer,
        @SerialName("story_id")
        @get:JvmName("storyId")
        public val storyId: Int,
        @get:JvmName("reaction")
        public val reaction: Reaction,
    ) : Update {
        public companion object
    }

    @Serializable
    @SerialName("updateBotChatBoost")
    @TLCombinatorId(0x904DD49C)
    public data class UpdateBotChatBoost(
        @get:JvmName("peer")
        public val peer: Peer,
        @get:JvmName("boost")
        public val boost: Boost,
        @get:JvmName("qts")
        public val qts: Int,
    ) : Update {
        public companion object
    }

    public companion object
}
