// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("wallPaperSettings")
@TLCombinatorId(0x1DC1BCA4)
public data class WallPaperSettings(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 1)
    @get:JvmName("blur")
    public val blur: Unit? = null,
    @TLConditional("flags", 2)
    @get:JvmName("motion")
    public val motion: Unit? = null,
    @SerialName("background_color")
    @TLConditional("flags", 0)
    @get:JvmName("backgroundColor")
    public val backgroundColor: Int? = null,
    @SerialName("second_background_color")
    @TLConditional("flags", 4)
    @get:JvmName("secondBackgroundColor")
    public val secondBackgroundColor: Int? = null,
    @SerialName("third_background_color")
    @TLConditional("flags", 5)
    @get:JvmName("thirdBackgroundColor")
    public val thirdBackgroundColor: Int? = null,
    @SerialName("fourth_background_color")
    @TLConditional("flags", 6)
    @get:JvmName("fourthBackgroundColor")
    public val fourthBackgroundColor: Int? = null,
    @TLConditional("flags", 3)
    @get:JvmName("intensity")
    public val intensity: Int? = null,
    @TLConditional("flags", 4)
    @get:JvmName("rotation")
    public val rotation: Int? = null,
) {
    public companion object
}
