// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.secret

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface DocumentAttribute {
    @Serializable
    @SerialName("documentAttributeImageSize")
    @TLCombinatorId(0x6C37C15C)
    public data class DocumentAttributeImageSize(
        @get:JvmName("w")
        public val w: Int,
        @get:JvmName("h")
        public val h: Int,
    ) : DocumentAttribute {
        public companion object
    }

    @Serializable
    @SerialName("documentAttributeAnimated")
    @TLCombinatorId(0x11B58939)
    public object DocumentAttributeAnimated : DocumentAttribute

    @Serializable
    @SerialName("documentAttributeSticker23")
    @TLCombinatorId(0xFB0A5727)
    public object DocumentAttributeSticker23 : DocumentAttribute

    @Serializable
    @SerialName("documentAttributeVideo23")
    @TLCombinatorId(0x5910CCCB)
    public data class DocumentAttributeVideo23(
        @get:JvmName("duration")
        public val duration: Int,
        @get:JvmName("w")
        public val w: Int,
        @get:JvmName("h")
        public val h: Int,
    ) : DocumentAttribute {
        public companion object
    }

    @Serializable
    @SerialName("documentAttributeAudio23")
    @TLCombinatorId(0x51448E5)
    public data class DocumentAttributeAudio23(
        @get:JvmName("duration")
        public val duration: Int,
    ) : DocumentAttribute {
        public companion object
    }

    @Serializable
    @SerialName("documentAttributeFilename")
    @TLCombinatorId(0x15590068)
    public data class DocumentAttributeFilename(
        @SerialName("file_name")
        @get:JvmName("fileName")
        public val fileName: String,
    ) : DocumentAttribute {
        public companion object
    }

    @Serializable
    @SerialName("documentAttributeAudio45")
    @TLCombinatorId(0xDED218E0)
    public data class DocumentAttributeAudio45(
        @get:JvmName("duration")
        public val duration: Int,
        @get:JvmName("title")
        public val title: String,
        @get:JvmName("performer")
        public val performer: String,
    ) : DocumentAttribute {
        public companion object
    }

    @Serializable
    @SerialName("documentAttributeSticker")
    @TLCombinatorId(0x3A556302)
    public data class DocumentAttributeSticker(
        @get:JvmName("alt")
        public val alt: String,
        @get:JvmName("stickerset")
        public val stickerset: InputStickerSet,
    ) : DocumentAttribute {
        public companion object
    }

    @Serializable
    @SerialName("documentAttributeAudio")
    @TLCombinatorId(0x9852F9C6)
    public data class DocumentAttributeAudio(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 10)
        @get:JvmName("voice")
        public val voice: Unit? = null,
        @get:JvmName("duration")
        public val duration: Int,
        @TLConditional("flags", 0)
        @get:JvmName("title")
        public val title: String? = null,
        @TLConditional("flags", 1)
        @get:JvmName("performer")
        public val performer: String? = null,
        @TLConditional("flags", 2)
        @get:JvmName("waveform")
        public val waveform: @Serializable(Base64ByteStringSerializer::class) ByteString? = null,
    ) : DocumentAttribute {
        public companion object
    }

    @Serializable
    @SerialName("documentAttributeVideo")
    @TLCombinatorId(0xEF02CE6)
    public data class DocumentAttributeVideo(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("round_message")
        @TLConditional("flags", 0)
        @get:JvmName("roundMessage")
        public val roundMessage: Unit? = null,
        @get:JvmName("duration")
        public val duration: Int,
        @get:JvmName("w")
        public val w: Int,
        @get:JvmName("h")
        public val h: Int,
    ) : DocumentAttribute {
        public companion object
    }

    public companion object
}
