// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.secret

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface InputStickerSet {
    @Serializable
    @SerialName("inputStickerSetShortName")
    @TLCombinatorId(0x861CC8A0)
    public data class InputStickerSetShortName(
        @SerialName("short_name")
        @get:JvmName("shortName")
        public val shortName: String,
    ) : InputStickerSet {
        public companion object
    }

    @Serializable
    @SerialName("inputStickerSetEmpty")
    @TLCombinatorId(0xFFB62B95)
    public object InputStickerSetEmpty : InputStickerSet

    public companion object
}
