// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.tonlib.msg

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("msg.dataEncryptedArray")
@TLCombinatorId(0x244759B2)
public data class MsgDataEncryptedArray(
    @get:JvmName("elements")
    public val elements: List<MsgDataEncrypted>,
) {
    public companion object
}
