// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.validator.config

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.tonnode.TonNodeBlockIdExt

@Serializable
@SerialName("validator.config.global")
@TLCombinatorId(0x867DFF6A)
public data class ValidatorConfigGlobal(
    @SerialName("zero_state")
    @get:JvmName("zeroState")
    public val zeroState: TonNodeBlockIdExt,
    @SerialName("init_block")
    @get:JvmName("initBlock")
    public val initBlock: TonNodeBlockIdExt,
    @get:JvmName("hardforks")
    public val hardforks: List<TonNodeBlockIdExt>,
) {
    public companion object
}
