// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.stickers

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("stickers.suggestedShortName")
@TLCombinatorId(0x85FEA03F)
public data class StickersSuggestedShortName(
    @SerialName("short_name")
    @get:JvmName("shortName")
    public val shortName: String,
) {
    public companion object
}
