// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.db.celldb

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.tonnode.TonNodeBlockIdExt

@Serializable
@SerialName("db.celldb.value")
@TLCombinatorId(0xE6101440)
public data class DbCelldbValue(
    @SerialName("block_id")
    @get:JvmName("blockId")
    public val blockId: TonNodeBlockIdExt,
    @TLFixedSize(value = 32)
    @get:JvmName("prev")
    public val prev: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @TLFixedSize(value = 32)
    @get:JvmName("next")
    public val next: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @SerialName("root_hash")
    @TLFixedSize(value = 32)
    @get:JvmName("rootHash")
    public val rootHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
