// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.tonlib.smc

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("smc.libraryResult")
@TLCombinatorId(0x0C27BBFE)
public data class SmcLibraryResult(
    @get:JvmName("result")
    public val result: List<SmcLibraryEntry>,
) {
    public companion object
}
