// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.liteserver.debug

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("liteServer.debug.verbosity")
@TLCombinatorId(0x5D404733)
public data class LiteServerDebugVerbosity(
    @get:JvmName("value")
    public val `value`: Int,
) {
    public companion object
}
