// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.liteclient.config

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.liteserver.LiteserverDesc
import tl.ton.validator.config.ValidatorConfigGlobal

@Serializable
@SerialName("liteclient.config.global")
@TLCombinatorId(0x088DC0F8)
public data class LiteclientConfigGlobal(
    @get:JvmName("liteservers")
    public val liteservers: List<LiteserverDesc>,
    @get:JvmName("validator")
    public val validator: ValidatorConfigGlobal,
) {
    public companion object
}
