// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.help

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.Document
import tl.telegram.MessageEntity
import tl.telegram.PremiumSubscriptionOption
import tl.telegram.User

@Serializable
@SerialName("help.premiumPromo")
@TLCombinatorId(0x5334759C)
public data class HelpPremiumPromo(
    @SerialName("status_text")
    @get:JvmName("statusText")
    public val statusText: String,
    @SerialName("status_entities")
    @get:JvmName("statusEntities")
    public val statusEntities: List<MessageEntity>,
    @SerialName("video_sections")
    @get:JvmName("videoSections")
    public val videoSections: List<String>,
    @get:JvmName("videos")
    public val videos: List<Document>,
    @SerialName("period_options")
    @get:JvmName("periodOptions")
    public val periodOptions: List<PremiumSubscriptionOption>,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
