// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.help

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.AccessPointRule

@Serializable
@SerialName("help.configSimple")
@TLCombinatorId(0x5A592A6C)
public data class HelpConfigSimple(
    @get:JvmName("date")
    public val date: Int,
    @get:JvmName("expires")
    public val expires: Int,
    @get:JvmName("rules")
    public val rules: List<AccessPointRule>,
) {
    public companion object
}
