// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.help

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface HelpCountriesList {
    @Serializable
    @SerialName("help.countriesListNotModified")
    @TLCombinatorId(0x93CC1F32)
    public object CountriesListNotModified : HelpCountriesList

    @Serializable
    @SerialName("help.countriesList")
    @TLCombinatorId(0x87D0759E)
    public data class CountriesList(
        @get:JvmName("countries")
        public val countries: List<HelpCountry>,
        @get:JvmName("hash")
        public val hash: Int,
    ) : HelpCountriesList {
        public companion object
    }

    public companion object
}
