// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.help

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.DataJSON
import tl.telegram.MessageEntity

@Serializable
@SerialName("help.termsOfService")
@TLCombinatorId(0x780A0310)
public data class HelpTermsOfService(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("popup")
    public val popup: Unit? = null,
    @get:JvmName("id")
    public val id: DataJSON,
    @get:JvmName("text")
    public val text: String,
    @get:JvmName("entities")
    public val entities: List<MessageEntity>,
    @SerialName("min_age_confirm")
    @TLConditional("flags", 1)
    @get:JvmName("minAgeConfirm")
    public val minAgeConfirm: Int? = null,
) {
    public companion object
}
