// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.liteserver

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.tonnode.TonNodeBlockIdExt

@Serializable
@SerialName("liteServer.transactionList")
@TLCombinatorId(0x6F26C60B)
public data class LiteServerTransactionList(
    @get:JvmName("ids")
    public val ids: List<TonNodeBlockIdExt>,
    @get:JvmName("transactions")
    public val transactions: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
