// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.liteserver

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.tonnode.TonNodeBlockIdExt

@Serializable
@SerialName("liteServer.blockTransactions")
@TLCombinatorId(0xBD8CAD2B)
public data class LiteServerBlockTransactions(
    @get:JvmName("id")
    public val id: TonNodeBlockIdExt,
    @SerialName("req_count")
    @get:JvmName("reqCount")
    public val reqCount: Int,
    @get:JvmName("incomplete")
    public val incomplete: Boolean,
    @get:JvmName("ids")
    public val ids: List<LiteServerTransactionId>,
    @get:JvmName("proof")
    public val proof: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
