// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.liteserver

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("liteServer.sendMsgStatus")
@TLCombinatorId(0x3950E597)
public data class LiteServerSendMsgStatus(
    @get:JvmName("status")
    public val status: Int,
) {
    public companion object
}
