// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.liteserver

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.tonnode.TonNodeBlockIdExt

@Serializable
@SerialName("liteServer.transactionInfo")
@TLCombinatorId(0x0EDEED47)
public data class LiteServerTransactionInfo(
    @get:JvmName("id")
    public val id: TonNodeBlockIdExt,
    @get:JvmName("proof")
    public val proof: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("transaction")
    public val transaction: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
