// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.liteserver

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.tonnode.TonNodeBlockIdExt

@Serializable
@SerialName("liteServer.shardInfo")
@TLCombinatorId(0x9FE6CD84)
public data class LiteServerShardInfo(
    @get:JvmName("id")
    public val id: TonNodeBlockIdExt,
    @get:JvmName("shardblk")
    public val shardblk: TonNodeBlockIdExt,
    @SerialName("shard_proof")
    @get:JvmName("shardProof")
    public val shardProof: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @SerialName("shard_descr")
    @get:JvmName("shardDescr")
    public val shardDescr: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
