// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.liteserver

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("liteServer.currentTime")
@TLCombinatorId(0xE953000D)
public data class LiteServerCurrentTime(
    @get:JvmName("now")
    public val now: Int,
) {
    public companion object
}
