// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.liteserver

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.tonnode.TonNodeBlockIdExt

@Serializable
@SerialName("liteServer.shardBlockProof")
@TLCombinatorId(0x1D62A07A)
public data class LiteServerShardBlockProof(
    @SerialName("masterchain_id")
    @get:JvmName("masterchainId")
    public val masterchainId: TonNodeBlockIdExt,
    @get:JvmName("links")
    public val links: List<LiteServerShardBlockLink>,
) {
    public companion object
}
