// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.liteserver

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.tonnode.TonNodeBlockIdExt

@Serializable
@SerialName("liteServer.accountState")
@TLCombinatorId(0x7079C751)
public data class LiteServerAccountState(
    @get:JvmName("id")
    public val id: TonNodeBlockIdExt,
    @get:JvmName("shardblk")
    public val shardblk: TonNodeBlockIdExt,
    @SerialName("shard_proof")
    @get:JvmName("shardProof")
    public val shardProof: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("proof")
    public val proof: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("state")
    public val state: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
