// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.tonlib.pchan

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("pchan.promise")
@TLCombinatorId(0xA20E945D)
public data class PchanPromise(
    @get:JvmName("signature")
    public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @SerialName("promise_A")
    @get:JvmName("promiseA")
    public val promiseA: Long,
    @SerialName("promise_B")
    @get:JvmName("promiseB")
    public val promiseB: Long,
    @SerialName("channel_id")
    @get:JvmName("channelId")
    public val channelId: Long,
) {
    public companion object
}
