// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.mtproto

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("msg_resend_req")
@TLCombinatorId(0x7D861A08)
public data class MsgResendReq(
    @SerialName("msg_ids")
    @get:JvmName("msgIds")
    public val msgIds: List<Long>,
) {
    public companion object
}
