// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.mtproto

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("rpc_error")
@TLCombinatorId(0x2144CA19)
public data class RpcError(
    @SerialName("error_code")
    @get:JvmName("errorCode")
    public val errorCode: Int,
    @SerialName("error_message")
    @get:JvmName("errorMessage")
    public val errorMessage: String,
) {
    public companion object
}
