// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.tonlib.raw

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.tonlib.AccountAddress
import tl.tonlib.msg.MsgData

@Serializable
@SerialName("raw.message")
@TLCombinatorId(0x518B724F)
public data class RawMessage(
    @get:JvmName("source")
    public val source: AccountAddress,
    @get:JvmName("destination")
    public val destination: AccountAddress,
    @get:JvmName("value")
    public val `value`: Long,
    @SerialName("fwd_fee")
    @get:JvmName("fwdFee")
    public val fwdFee: Long,
    @SerialName("ihr_fee")
    @get:JvmName("ihrFee")
    public val ihrFee: Long,
    @SerialName("created_lt")
    @get:JvmName("createdLt")
    public val createdLt: Long,
    @SerialName("body_hash")
    @get:JvmName("bodyHash")
    public val bodyHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @SerialName("msg_data")
    @get:JvmName("msgData")
    public val msgData: MsgData,
) {
    public companion object
}
