// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.upload

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import tl.telegram.FileHash
import tl.telegram.storage.StorageFileType

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface UploadFile {
    @Serializable
    @SerialName("upload.file")
    @TLCombinatorId(0x96A18D5)
    public data class File(
        @get:JvmName("type")
        public val type: StorageFileType,
        @get:JvmName("mtime")
        public val mtime: Int,
        @get:JvmName("bytes")
        public val bytes: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : UploadFile {
        public companion object
    }

    @Serializable
    @SerialName("upload.fileCdnRedirect")
    @TLCombinatorId(0xF18CDA44)
    public data class FileCdnRedirect(
        @SerialName("dc_id")
        @get:JvmName("dcId")
        public val dcId: Int,
        @SerialName("file_token")
        @get:JvmName("fileToken")
        public val fileToken: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("encryption_key")
        @get:JvmName("encryptionKey")
        public val encryptionKey: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("encryption_iv")
        @get:JvmName("encryptionIv")
        public val encryptionIv: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("file_hashes")
        @get:JvmName("fileHashes")
        public val fileHashes: List<FileHash>,
    ) : UploadFile {
        public companion object
    }

    public companion object
}
