// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.id.config

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.PrivateKey

@Serializable
@SerialName("id.config.local")
@TLCombinatorId(0x92A9C78E)
public data class IdConfigLocal(
    @get:JvmName("id")
    public val id: PrivateKey,
) {
    public companion object
}
