// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.payments

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("payments.exportedInvoice")
@TLCombinatorId(0xAED0CBD9)
public data class PaymentsExportedInvoice(
    @get:JvmName("url")
    public val url: String,
) {
    public companion object
}
