// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.payments

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface PaymentsGiveawayInfo {
    @Serializable
    @SerialName("payments.giveawayInfo")
    @TLCombinatorId(0x4367DAA0)
    public data class GiveawayInfo(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("participating")
        public val participating: Unit? = null,
        @SerialName("preparing_results")
        @TLConditional("flags", 3)
        @get:JvmName("preparingResults")
        public val preparingResults: Unit? = null,
        @SerialName("start_date")
        @get:JvmName("startDate")
        public val startDate: Int,
        @SerialName("joined_too_early_date")
        @TLConditional("flags", 1)
        @get:JvmName("joinedTooEarlyDate")
        public val joinedTooEarlyDate: Int? = null,
        @SerialName("admin_disallowed_chat_id")
        @TLConditional("flags", 2)
        @get:JvmName("adminDisallowedChatId")
        public val adminDisallowedChatId: Long? = null,
        @SerialName("disallowed_country")
        @TLConditional("flags", 4)
        @get:JvmName("disallowedCountry")
        public val disallowedCountry: String? = null,
    ) : PaymentsGiveawayInfo {
        public companion object
    }

    @Serializable
    @SerialName("payments.giveawayInfoResults")
    @TLCombinatorId(0xCD5570)
    public data class GiveawayInfoResults(
        @get:JvmName("flags")
        public val flags: Int,
        @TLConditional("flags", 0)
        @get:JvmName("winner")
        public val winner: Unit? = null,
        @TLConditional("flags", 1)
        @get:JvmName("refunded")
        public val refunded: Unit? = null,
        @SerialName("start_date")
        @get:JvmName("startDate")
        public val startDate: Int,
        @SerialName("gift_code_slug")
        @TLConditional("flags", 0)
        @get:JvmName("giftCodeSlug")
        public val giftCodeSlug: String? = null,
        @SerialName("finish_date")
        @get:JvmName("finishDate")
        public val finishDate: Int,
        @SerialName("winners_count")
        @get:JvmName("winnersCount")
        public val winnersCount: Int,
        @SerialName("activated_count")
        @get:JvmName("activatedCount")
        public val activatedCount: Int,
    ) : PaymentsGiveawayInfo {
        public companion object
    }

    public companion object
}
