// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.ExportedChatInvite
import tl.telegram.User

@Serializable
@SerialName("messages.exportedChatInvites")
@TLCombinatorId(0xBDC62DCC)
public data class MessagesExportedChatInvites(
    @get:JvmName("count")
    public val count: Int,
    @get:JvmName("invites")
    public val invites: List<ExportedChatInvite>,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
