// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("messages.historyImportParsed")
@TLCombinatorId(0x5E0FB7B9)
public data class MessagesHistoryImportParsed(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("pm")
    public val pm: Unit? = null,
    @TLConditional("flags", 1)
    @get:JvmName("group")
    public val group: Unit? = null,
    @TLConditional("flags", 2)
    @get:JvmName("title")
    public val title: String? = null,
) {
    public companion object
}
