// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.BotInlineResult
import tl.telegram.InlineBotSwitchPM
import tl.telegram.InlineBotWebView
import tl.telegram.User

@Serializable
@SerialName("messages.botResults")
@TLCombinatorId(0xE021F2F6)
public data class MessagesBotResults(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("gallery")
    public val gallery: Unit? = null,
    @SerialName("query_id")
    @get:JvmName("queryId")
    public val queryId: Long,
    @SerialName("next_offset")
    @TLConditional("flags", 1)
    @get:JvmName("nextOffset")
    public val nextOffset: String? = null,
    @SerialName("switch_pm")
    @TLConditional("flags", 2)
    @get:JvmName("switchPm")
    public val switchPm: InlineBotSwitchPM? = null,
    @SerialName("switch_webview")
    @TLConditional("flags", 3)
    @get:JvmName("switchWebview")
    public val switchWebview: InlineBotWebView? = null,
    @get:JvmName("results")
    public val results: List<BotInlineResult>,
    @SerialName("cache_time")
    @get:JvmName("cacheTime")
    public val cacheTime: Int,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
