// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.Chat
import tl.telegram.PeerSettings
import tl.telegram.User

@Serializable
@SerialName("messages.peerSettings")
@TLCombinatorId(0x6880B94D)
public data class MessagesPeerSettings(
    @get:JvmName("settings")
    public val settings: PeerSettings,
    @get:JvmName("chats")
    public val chats: List<Chat>,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
