// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.MessagesFilter

@Serializable
@SerialName("messages.searchCounter")
@TLCombinatorId(0xE844EBFF)
public data class MessagesSearchCounter(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 1)
    @get:JvmName("inexact")
    public val inexact: Unit? = null,
    @get:JvmName("filter")
    public val filter: MessagesFilter,
    @get:JvmName("count")
    public val count: Int,
) {
    public companion object
}
