// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.Chat
import tl.telegram.MessageViews
import tl.telegram.User

@Serializable
@SerialName("messages.messageViews")
@TLCombinatorId(0xB6C4F543)
public data class MessagesMessageViews(
    @get:JvmName("views")
    public val views: List<MessageViews>,
    @get:JvmName("chats")
    public val chats: List<Chat>,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
