// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.Chat
import tl.telegram.MessagePeerVote
import tl.telegram.User

@Serializable
@SerialName("messages.votesList")
@TLCombinatorId(0x4899484E)
public data class MessagesVotesList(
    @get:JvmName("flags")
    public val flags: Int,
    @get:JvmName("count")
    public val count: Int,
    @get:JvmName("votes")
    public val votes: List<MessagePeerVote>,
    @get:JvmName("chats")
    public val chats: List<Chat>,
    @get:JvmName("users")
    public val users: List<User>,
    @SerialName("next_offset")
    @TLConditional("flags", 0)
    @get:JvmName("nextOffset")
    public val nextOffset: String? = null,
) {
    public companion object
}
