// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.ChatAdminWithInvites
import tl.telegram.User

@Serializable
@SerialName("messages.chatAdminsWithInvites")
@TLCombinatorId(0xB69B72D7)
public data class MessagesChatAdminsWithInvites(
    @get:JvmName("admins")
    public val admins: List<ChatAdminWithInvites>,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
