// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import tl.telegram.StickerSet

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface MessagesAllStickers {
    @Serializable
    @SerialName("messages.allStickersNotModified")
    @TLCombinatorId(0xE86602C3)
    public object AllStickersNotModified : MessagesAllStickers

    @Serializable
    @SerialName("messages.allStickers")
    @TLCombinatorId(0xCDBBCEBB)
    public data class AllStickers(
        @get:JvmName("hash")
        public val hash: Long,
        @get:JvmName("sets")
        public val sets: List<StickerSet>,
    ) : MessagesAllStickers {
        public companion object
    }

    public companion object
}
