// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.Chat
import tl.telegram.Message
import tl.telegram.SearchResultsCalendarPeriod
import tl.telegram.User

@Serializable
@SerialName("messages.searchResultsCalendar")
@TLCombinatorId(0x147EE23C)
public data class MessagesSearchResultsCalendar(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("inexact")
    public val inexact: Unit? = null,
    @get:JvmName("count")
    public val count: Int,
    @SerialName("min_date")
    @get:JvmName("minDate")
    public val minDate: Int,
    @SerialName("min_msg_id")
    @get:JvmName("minMsgId")
    public val minMsgId: Int,
    @SerialName("offset_id_offset")
    @TLConditional("flags", 1)
    @get:JvmName("offsetIdOffset")
    public val offsetIdOffset: Int? = null,
    @get:JvmName("periods")
    public val periods: List<SearchResultsCalendarPeriod>,
    @get:JvmName("messages")
    public val messages: List<Message>,
    @get:JvmName("chats")
    public val chats: List<Chat>,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
