// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("messages.affectedMessages")
@TLCombinatorId(0x84D19185)
public data class MessagesAffectedMessages(
    @get:JvmName("pts")
    public val pts: Int,
    @SerialName("pts_count")
    @get:JvmName("ptsCount")
    public val ptsCount: Int,
) {
    public companion object
}
