// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.messages

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import tl.telegram.Chat

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface MessagesChats {
    @Serializable
    @SerialName("messages.chats")
    @TLCombinatorId(0x64FF9FD5)
    public data class Chats(
        @get:JvmName("chats")
        public val chats: List<Chat>,
    ) : MessagesChats {
        public companion object
    }

    @Serializable
    @SerialName("messages.chatsSlice")
    @TLCombinatorId(0x9CD81144)
    public data class ChatsSlice(
        @get:JvmName("count")
        public val count: Int,
        @get:JvmName("chats")
        public val chats: List<Chat>,
    ) : MessagesChats {
        public companion object
    }

    public companion object
}
