// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.catchain

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface CatchainBlockResult {
    @Serializable
    @SerialName("catchain.blockNotFound")
    @TLCombinatorId(0xB6110884)
    public object BlockNotFound : CatchainBlockResult

    @Serializable
    @SerialName("catchain.blockResult")
    @TLCombinatorId(0x9D2A3047)
    public data class BlockResult(
        @get:JvmName("block")
        public val block: CatchainBlock,
    ) : CatchainBlockResult {
        public companion object
    }

    public companion object
}
