// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.storage.db

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface StorageDbTorrentShort {
    @Serializable
    @SerialName("storage.db.torrent")
    @TLCombinatorId(0xAD2D379A)
    public data class Torrent(
        @SerialName("root_dir")
        @get:JvmName("rootDir")
        public val rootDir: String,
        @SerialName("active_download")
        @get:JvmName("activeDownload")
        public val activeDownload: Boolean,
        @SerialName("active_upload")
        @get:JvmName("activeUpload")
        public val activeUpload: Boolean,
    ) : StorageDbTorrentShort {
        public companion object
    }

    @Serializable
    @SerialName("storage.db.torrentV2")
    @TLCombinatorId(0x89ECF89B)
    public data class TorrentV2(
        @get:JvmName("flags")
        public val flags: Int,
        @SerialName("root_dir")
        @get:JvmName("rootDir")
        public val rootDir: String,
        @SerialName("added_at")
        @get:JvmName("addedAt")
        public val addedAt: Int,
        @SerialName("active_download")
        @get:JvmName("activeDownload")
        public val activeDownload: Boolean,
        @SerialName("active_upload")
        @get:JvmName("activeUpload")
        public val activeUpload: Boolean,
    ) : StorageDbTorrentShort {
        public companion object
    }

    public companion object
}
