// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.premium

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.PrepaidGiveaway
import tl.telegram.StatsPercentValue

@Serializable
@SerialName("premium.boostsStatus")
@TLCombinatorId(0x4959427A)
public data class PremiumBoostsStatus(
    @get:JvmName("flags")
    public val flags: Int,
    @SerialName("my_boost")
    @TLConditional("flags", 2)
    @get:JvmName("myBoost")
    public val myBoost: Unit? = null,
    @get:JvmName("level")
    public val level: Int,
    @SerialName("current_level_boosts")
    @get:JvmName("currentLevelBoosts")
    public val currentLevelBoosts: Int,
    @get:JvmName("boosts")
    public val boosts: Int,
    @SerialName("gift_boosts")
    @TLConditional("flags", 4)
    @get:JvmName("giftBoosts")
    public val giftBoosts: Int? = null,
    @SerialName("next_level_boosts")
    @TLConditional("flags", 0)
    @get:JvmName("nextLevelBoosts")
    public val nextLevelBoosts: Int? = null,
    @SerialName("premium_audience")
    @TLConditional("flags", 1)
    @get:JvmName("premiumAudience")
    public val premiumAudience: StatsPercentValue? = null,
    @SerialName("boost_url")
    @get:JvmName("boostUrl")
    public val boostUrl: String,
    @SerialName("prepaid_giveaways")
    @TLConditional("flags", 3)
    @get:JvmName("prepaidGiveaways")
    public val prepaidGiveaways: List<PrepaidGiveaway>? = null,
    @SerialName("my_boost_slots")
    @TLConditional("flags", 2)
    @get:JvmName("myBoostSlots")
    public val myBoostSlots: List<Int>? = null,
) {
    public companion object
}
