// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.catchain.config

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.PublicKey

@Serializable
@SerialName("catchain.config.global")
@TLCombinatorId(0x68C7B651)
public data class CatchainConfigGlobal(
    @TLFixedSize(value = 32)
    @get:JvmName("tag")
    public val tag: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("nodes")
    public val nodes: List<PublicKey>,
) {
    public companion object
}
