// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.phone

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.Chat
import tl.telegram.GroupCallParticipant
import tl.telegram.User

@Serializable
@SerialName("phone.groupParticipants")
@TLCombinatorId(0xF47751B6)
public data class PhoneGroupParticipants(
    @get:JvmName("count")
    public val count: Int,
    @get:JvmName("participants")
    public val participants: List<GroupCallParticipant>,
    @SerialName("next_offset")
    @get:JvmName("nextOffset")
    public val nextOffset: String,
    @get:JvmName("chats")
    public val chats: List<Chat>,
    @get:JvmName("users")
    public val users: List<User>,
    @get:JvmName("version")
    public val version: Int,
) {
    public companion object
}
