// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.phone

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.PhoneCall
import tl.telegram.User

@Serializable
@SerialName("phone.phoneCall")
@TLCombinatorId(0xEC82E140)
public data class PhonePhoneCall(
    @SerialName("phone_call")
    @get:JvmName("phoneCall")
    public val phoneCall: PhoneCall,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
