// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.storage

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("storage.piece")
@TLCombinatorId(0x80B4FA0D)
public data class StoragePiece(
    @get:JvmName("proof")
    public val proof: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("data")
    public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
