// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.storage

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface StorageUpdate {
    @Serializable
    @SerialName("storage.updateInit")
    @TLCombinatorId(0xCE33E0B6)
    public data class UpdateInit(
        @SerialName("have_pieces")
        @get:JvmName("havePieces")
        public val havePieces: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("have_pieces_offset")
        @get:JvmName("havePiecesOffset")
        public val havePiecesOffset: Int,
        @get:JvmName("state")
        public val state: StorageState,
    ) : StorageUpdate {
        public companion object
    }

    @Serializable
    @SerialName("storage.updateHavePieces")
    @TLCombinatorId(0x3BF82049)
    public data class UpdateHavePieces(
        @SerialName("piece_id")
        @get:JvmName("pieceId")
        public val pieceId: List<Int>,
    ) : StorageUpdate {
        public companion object
    }

    @Serializable
    @SerialName("storage.updateState")
    @TLCombinatorId(0x05B034B5)
    public data class UpdateState(
        @get:JvmName("state")
        public val state: StorageState,
    ) : StorageUpdate {
        public companion object
    }

    public companion object
}
