// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.storage

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("storage.pong")
@TLCombinatorId(0x6CF5C6A5)
public object StoragePong
