// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.auth

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("auth.exportedAuthorization")
@TLCombinatorId(0xB434E2B8)
public data class AuthExportedAuthorization(
    @get:JvmName("id")
    public val id: Long,
    @get:JvmName("bytes")
    public val bytes: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
