// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.auth

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("auth.passwordRecovery")
@TLCombinatorId(0x137948A5)
public data class AuthPasswordRecovery(
    @SerialName("email_pattern")
    @get:JvmName("emailPattern")
    public val emailPattern: String,
) {
    public companion object
}
