// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.auth

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface AuthLoginToken {
    @Serializable
    @SerialName("auth.loginToken")
    @TLCombinatorId(0x629F1980)
    public data class LoginToken(
        @get:JvmName("expires")
        public val expires: Int,
        @get:JvmName("token")
        public val token: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : AuthLoginToken {
        public companion object
    }

    @Serializable
    @SerialName("auth.loginTokenMigrateTo")
    @TLCombinatorId(0x68E9916)
    public data class LoginTokenMigrateTo(
        @SerialName("dc_id")
        @get:JvmName("dcId")
        public val dcId: Int,
        @get:JvmName("token")
        public val token: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : AuthLoginToken {
        public companion object
    }

    @Serializable
    @SerialName("auth.loginTokenSuccess")
    @TLCombinatorId(0x390D5C5E)
    public data class LoginTokenSuccess(
        @get:JvmName("authorization")
        public val authorization: AuthAuthorization,
    ) : AuthLoginToken {
        public companion object
    }

    public companion object
}
