// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.auth

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class AuthCodeType {
    @SerialName("auth.codeTypeSms")
    @TLCombinatorId(0x72A3158C)
    CODE_TYPE_SMS,
    @SerialName("auth.codeTypeCall")
    @TLCombinatorId(0x741CD3E3)
    CODE_TYPE_CALL,
    @SerialName("auth.codeTypeFlashCall")
    @TLCombinatorId(0x226CCEFB)
    CODE_TYPE_FLASH_CALL,
    @SerialName("auth.codeTypeMissedCall")
    @TLCombinatorId(0xD61AD6EE)
    CODE_TYPE_MISSED_CALL,
    @SerialName("auth.codeTypeFragmentSms")
    @TLCombinatorId(0x6ED998C)
    CODE_TYPE_FRAGMENT_SMS,
    ;

    public companion object
}
