// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.tonlib.liteserver

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("liteServer.info")
@TLCombinatorId(0xB57BFE73)
public data class LiteServerInfo(
    @get:JvmName("now")
    public val now: Long,
    @get:JvmName("version")
    public val version: Int,
    @get:JvmName("capabilities")
    public val capabilities: Long,
) {
    public companion object
}
