// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.contacts

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.Chat
import tl.telegram.Peer
import tl.telegram.User

@Serializable
@SerialName("contacts.found")
@TLCombinatorId(0xB3134D9D)
public data class ContactsFound(
    @SerialName("my_results")
    @get:JvmName("myResults")
    public val myResults: List<Peer>,
    @get:JvmName("results")
    public val results: List<Peer>,
    @get:JvmName("chats")
    public val chats: List<Chat>,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
