// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.engine.adnlproxy

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.adnl.AdnlProxy

@Serializable
@SerialName("engine.adnlProxy.port")
@TLCombinatorId(0xF901754A)
public data class EngineAdnlProxyPort(
    @SerialName("in_port")
    @get:JvmName("inPort")
    public val inPort: Int,
    @SerialName("out_port")
    @get:JvmName("outPort")
    public val outPort: Int,
    @SerialName("dst_ip")
    @get:JvmName("dstIp")
    public val dstIp: Int,
    @SerialName("dst_port")
    @get:JvmName("dstPort")
    public val dstPort: Int,
    @SerialName("proxy_type")
    @get:JvmName("proxyType")
    public val proxyType: AdnlProxy,
) {
    public companion object
}
