// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.tonlib.tvm

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface TvmStackEntry {
    @Serializable
    @SerialName("tvm.stackEntrySlice")
    @TLCombinatorId(0x532D6B25)
    public data class StackEntrySlice(
        @get:JvmName("slice")
        public val slice: TvmSlice,
    ) : TvmStackEntry {
        public companion object
    }

    @Serializable
    @SerialName("tvm.stackEntryCell")
    @TLCombinatorId(0x4DB16F20)
    public data class StackEntryCell(
        @get:JvmName("cell")
        public val cell: TvmCell,
    ) : TvmStackEntry {
        public companion object
    }

    @Serializable
    @SerialName("tvm.stackEntryNumber")
    @TLCombinatorId(0x50FB3DBE)
    public data class StackEntryNumber(
        @get:JvmName("number")
        public val number: TvmNumber,
    ) : TvmStackEntry {
        public companion object
    }

    @Serializable
    @SerialName("tvm.stackEntryTuple")
    @TLCombinatorId(0xF69E63DC)
    public data class StackEntryTuple(
        @get:JvmName("tuple")
        public val tuple: TvmTuple,
    ) : TvmStackEntry {
        public companion object
    }

    @Serializable
    @SerialName("tvm.stackEntryList")
    @TLCombinatorId(0xB9442D8B)
    public data class StackEntryList(
        @get:JvmName("list")
        public val list: TvmList,
    ) : TvmStackEntry {
        public companion object
    }

    @Serializable
    @SerialName("tvm.stackEntryUnsupported")
    @TLCombinatorId(0x169541F2)
    public object StackEntryUnsupported : TvmStackEntry

    public companion object
}
