// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.channels

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.ChannelParticipant
import tl.telegram.Chat
import tl.telegram.User

@Serializable
@SerialName("channels.channelParticipant")
@TLCombinatorId(0xDFB80317)
public data class ChannelsChannelParticipant(
    @get:JvmName("participant")
    public val participant: ChannelParticipant,
    @get:JvmName("chats")
    public val chats: List<Chat>,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
