// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.stats

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.StatsAbsValueAndPrev
import tl.telegram.StatsDateRangeDays
import tl.telegram.StatsGraph
import tl.telegram.StatsGroupTopAdmin
import tl.telegram.StatsGroupTopInviter
import tl.telegram.StatsGroupTopPoster
import tl.telegram.User

@Serializable
@SerialName("stats.megagroupStats")
@TLCombinatorId(0xEF7FF916)
public data class StatsMegagroupStats(
    @get:JvmName("period")
    public val period: StatsDateRangeDays,
    @get:JvmName("members")
    public val members: StatsAbsValueAndPrev,
    @get:JvmName("messages")
    public val messages: StatsAbsValueAndPrev,
    @get:JvmName("viewers")
    public val viewers: StatsAbsValueAndPrev,
    @get:JvmName("posters")
    public val posters: StatsAbsValueAndPrev,
    @SerialName("growth_graph")
    @get:JvmName("growthGraph")
    public val growthGraph: StatsGraph,
    @SerialName("members_graph")
    @get:JvmName("membersGraph")
    public val membersGraph: StatsGraph,
    @SerialName("new_members_by_source_graph")
    @get:JvmName("newMembersBySourceGraph")
    public val newMembersBySourceGraph: StatsGraph,
    @SerialName("languages_graph")
    @get:JvmName("languagesGraph")
    public val languagesGraph: StatsGraph,
    @SerialName("messages_graph")
    @get:JvmName("messagesGraph")
    public val messagesGraph: StatsGraph,
    @SerialName("actions_graph")
    @get:JvmName("actionsGraph")
    public val actionsGraph: StatsGraph,
    @SerialName("top_hours_graph")
    @get:JvmName("topHoursGraph")
    public val topHoursGraph: StatsGraph,
    @SerialName("weekdays_graph")
    @get:JvmName("weekdaysGraph")
    public val weekdaysGraph: StatsGraph,
    @SerialName("top_posters")
    @get:JvmName("topPosters")
    public val topPosters: List<StatsGroupTopPoster>,
    @SerialName("top_admins")
    @get:JvmName("topAdmins")
    public val topAdmins: List<StatsGroupTopAdmin>,
    @SerialName("top_inviters")
    @get:JvmName("topInviters")
    public val topInviters: List<StatsGroupTopInviter>,
    @get:JvmName("users")
    public val users: List<User>,
) {
    public companion object
}
