// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.stats

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.MessageInteractionCounters
import tl.telegram.StatsAbsValueAndPrev
import tl.telegram.StatsDateRangeDays
import tl.telegram.StatsGraph
import tl.telegram.StatsPercentValue

@Serializable
@SerialName("stats.broadcastStats")
@TLCombinatorId(0xBDF78394)
public data class StatsBroadcastStats(
    @get:JvmName("period")
    public val period: StatsDateRangeDays,
    @get:JvmName("followers")
    public val followers: StatsAbsValueAndPrev,
    @SerialName("views_per_post")
    @get:JvmName("viewsPerPost")
    public val viewsPerPost: StatsAbsValueAndPrev,
    @SerialName("shares_per_post")
    @get:JvmName("sharesPerPost")
    public val sharesPerPost: StatsAbsValueAndPrev,
    @SerialName("enabled_notifications")
    @get:JvmName("enabledNotifications")
    public val enabledNotifications: StatsPercentValue,
    @SerialName("growth_graph")
    @get:JvmName("growthGraph")
    public val growthGraph: StatsGraph,
    @SerialName("followers_graph")
    @get:JvmName("followersGraph")
    public val followersGraph: StatsGraph,
    @SerialName("mute_graph")
    @get:JvmName("muteGraph")
    public val muteGraph: StatsGraph,
    @SerialName("top_hours_graph")
    @get:JvmName("topHoursGraph")
    public val topHoursGraph: StatsGraph,
    @SerialName("interactions_graph")
    @get:JvmName("interactionsGraph")
    public val interactionsGraph: StatsGraph,
    @SerialName("iv_interactions_graph")
    @get:JvmName("ivInteractionsGraph")
    public val ivInteractionsGraph: StatsGraph,
    @SerialName("views_by_source_graph")
    @get:JvmName("viewsBySourceGraph")
    public val viewsBySourceGraph: StatsGraph,
    @SerialName("new_followers_by_source_graph")
    @get:JvmName("newFollowersBySourceGraph")
    public val newFollowersBySourceGraph: StatsGraph,
    @SerialName("languages_graph")
    @get:JvmName("languagesGraph")
    public val languagesGraph: StatsGraph,
    @SerialName("recent_message_interactions")
    @get:JvmName("recentMessageInteractions")
    public val recentMessageInteractions: List<MessageInteractionCounters>,
) {
    public companion object
}
