// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.engine.validator

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("engine.validator.fullNodeMaster")
@TLCombinatorId(0x8485F668)
public data class EngineValidatorFullNodeMaster(
    @get:JvmName("port")
    public val port: Int,
    @TLFixedSize(value = 32)
    @get:JvmName("adnl")
    public val adnl: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
