// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.engine.validator

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("validator.groupMember")
@TLCombinatorId(0x8B9465E4)
public data class EngineValidatorGroupMember(
    @SerialName("public_key_hash")
    @TLFixedSize(value = 32)
    @get:JvmName("publicKeyHash")
    public val publicKeyHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @TLFixedSize(value = 32)
    @get:JvmName("adnl")
    public val adnl: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("weight")
    public val weight: Long,
) {
    public companion object
}
