// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.dummyworkchain0.config

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("dummyworkchain0.config.global")
@TLCombinatorId(0xDA616ED3)
public data class Dummyworkchain0ConfigGlobal(
    @SerialName("zero_state_hash")
    @TLFixedSize(value = 32)
    @get:JvmName("zeroStateHash")
    public val zeroStateHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
