// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.db.state

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.tonnode.TonNodeBlockIdExt

@Serializable
@SerialName("db.state.asyncSerializer")
@TLCombinatorId(0xD32F29A1)
public data class DbStateAsyncSerializer(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
    @get:JvmName("last")
    public val last: TonNodeBlockIdExt,
    @SerialName("last_ts")
    @get:JvmName("lastTs")
    public val lastTs: Int,
) {
    public companion object
}
