// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.db.state

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("db.state.destroyedSessions")
@TLCombinatorId(0xADA8D984)
public data class DbStateDestroyedSessions(
    @get:JvmName("sessions")
    public val sessions: List<@Serializable(Base64ByteStringSerializer::class) ByteString>,
) {
    public companion object
}
