// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.db.blockdb

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import tl.ton.tonnode.TonNodeBlockIdExt

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface DbBlockdbKey {
    @Serializable
    @SerialName("db.blockdb.key.lru")
    @TLCombinatorId(0x50BC963A)
    public data class Lru(
        @get:JvmName("id")
        public val id: TonNodeBlockIdExt,
    ) : DbBlockdbKey {
        public companion object
    }

    @Serializable
    @SerialName("db.blockdb.key.value")
    @TLCombinatorId(0x7F57D173)
    public data class Value(
        @get:JvmName("id")
        public val id: TonNodeBlockIdExt,
    ) : DbBlockdbKey {
        public companion object
    }

    public companion object
}
