// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.account

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.Authorization

@Serializable
@SerialName("account.authorizations")
@TLCombinatorId(0x4BFF8EA0)
public data class AccountAuthorizations(
    @SerialName("authorization_ttl_days")
    @get:JvmName("authorizationTtlDays")
    public val authorizationTtlDays: Int,
    @get:JvmName("authorizations")
    public val authorizations: List<Authorization>,
) {
    public companion object
}
