// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.account

import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.SecureSecretSettings

@Serializable
@SerialName("account.passwordSettings")
@TLCombinatorId(0x9A5C33E5)
public data class AccountPasswordSettings(
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("email")
    public val email: String? = null,
    @SerialName("secure_settings")
    @TLConditional("flags", 1)
    @get:JvmName("secureSettings")
    public val secureSettings: SecureSecretSettings? = null,
) {
    public companion object
}
