// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.account

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import tl.telegram.WallPaper

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface AccountWallPapers {
    @Serializable
    @SerialName("account.wallPapersNotModified")
    @TLCombinatorId(0x1C199183)
    public object WallPapersNotModified : AccountWallPapers

    @Serializable
    @SerialName("account.wallPapers")
    @TLCombinatorId(0xCDC3858C)
    public data class WallPapers(
        @get:JvmName("hash")
        public val hash: Long,
        @get:JvmName("wallpapers")
        public val wallpapers: List<WallPaper>,
    ) : AccountWallPapers {
        public companion object
    }

    public companion object
}
