// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.account

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.telegram.AutoDownloadSettings

@Serializable
@SerialName("account.autoDownloadSettings")
@TLCombinatorId(0x63CACF26)
public data class AccountAutoDownloadSettings(
    @get:JvmName("low")
    public val low: AutoDownloadSettings,
    @get:JvmName("medium")
    public val medium: AutoDownloadSettings,
    @get:JvmName("high")
    public val high: AutoDownloadSettings,
) {
    public companion object
}
