// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.telegram.updates

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import tl.telegram.Chat
import tl.telegram.EncryptedMessage
import tl.telegram.Message
import tl.telegram.Update
import tl.telegram.User

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface UpdatesDifference {
    @Serializable
    @SerialName("updates.differenceEmpty")
    @TLCombinatorId(0x5D75A138)
    public data class DifferenceEmpty(
        @get:JvmName("date")
        public val date: Int,
        @get:JvmName("seq")
        public val seq: Int,
    ) : UpdatesDifference {
        public companion object
    }

    @Serializable
    @SerialName("updates.difference")
    @TLCombinatorId(0xF49CA0)
    public data class Difference(
        @SerialName("new_messages")
        @get:JvmName("newMessages")
        public val newMessages: List<Message>,
        @SerialName("new_encrypted_messages")
        @get:JvmName("newEncryptedMessages")
        public val newEncryptedMessages: List<EncryptedMessage>,
        @SerialName("other_updates")
        @get:JvmName("otherUpdates")
        public val otherUpdates: List<Update>,
        @get:JvmName("chats")
        public val chats: List<Chat>,
        @get:JvmName("users")
        public val users: List<User>,
        @get:JvmName("state")
        public val state: UpdatesState,
    ) : UpdatesDifference {
        public companion object
    }

    @Serializable
    @SerialName("updates.differenceSlice")
    @TLCombinatorId(0xA8FB1981)
    public data class DifferenceSlice(
        @SerialName("new_messages")
        @get:JvmName("newMessages")
        public val newMessages: List<Message>,
        @SerialName("new_encrypted_messages")
        @get:JvmName("newEncryptedMessages")
        public val newEncryptedMessages: List<EncryptedMessage>,
        @SerialName("other_updates")
        @get:JvmName("otherUpdates")
        public val otherUpdates: List<Update>,
        @get:JvmName("chats")
        public val chats: List<Chat>,
        @get:JvmName("users")
        public val users: List<User>,
        @SerialName("intermediate_state")
        @get:JvmName("intermediateState")
        public val intermediateState: UpdatesState,
    ) : UpdatesDifference {
        public companion object
    }

    @Serializable
    @SerialName("updates.differenceTooLong")
    @TLCombinatorId(0x4AFE8F6D)
    public data class DifferenceTooLong(
        @get:JvmName("pts")
        public val pts: Int,
    ) : UpdatesDifference {
        public companion object
    }

    public companion object
}
